### ISSUE TITLE
Safari web browser not refreshing search filters

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/WP-Job-Manager#1934] opened 2019-11-07 22:15 UTC
**Describe the bug**
Using the Safari browser. Go to https://surfadesk.com/ then click the Submit listing menu link.
Then back to the home page again notice that Filter by label: is not showing correct.

Console error code is:
Failed to load resource: the server responded with a status of 404 ()
https://surfadesk.com/wp-content/plugins/wp-job-manager-listing-labels/public/js/listing-labels.min.js.map

**To Reproduce**
1. Go to https://surfadesk.com/ 
2. Click on Submit listing meu link.
3. Click on logo to go back to the front page.
4. Notice that a search filter Label is missing information.

**Screenshots**
![Screen Shot 2019-11-07 at 14 53 27](https://user-images.githubusercontent.com/5323259/68423154-8ace6080-016f-11ea-819a-fe33834bd31c.png)

Notice that only the Filter by label: is seen and no options below it. The pins on the Google map are also hidden. One has to refresh the page then the Filter by label options show up.

**Expected behavior**
I expected Safari to show the various options under Filter by label.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.2.4
- WP Job Manager Version: 1.34.1
- PHP Version: 7.3
- Other important details: We are using a theme called Listify that packs multiple plugins into it.

Support told gave me this information in regards to this Safari bug:
"In relation to the query here, this is actually an issue still pending a complete fix by WP Job Manager. In the meantime, I would suggest on using version 1.32.3 of the plugin. You can have it downloaded from here: (https://github.com/Automattic/WP-Job-Manager/releases/tag/1.32.3)."

![Screen Shot 2019-11-07 at 17 12 57](https://user-images.githubusercontent.com/5323259/68432170-e4d82180-0181-11ea-8d33-d95e183d2780.png)

![Screen Shot 2019-11-07 at 17 13 49](https://user-images.githubusercontent.com/5323259/68432225-020cf000-0182-11ea-8d4c-37adb9bb899b.png)

**Comment by kimsson360** [comment] 2019-11-08 09:38
I think it is the same issue I have, and I assume everyone else using Listify with WPJM above 1.32.3.

I think the (new) owners of Astoundify/Listify should help out here! They respond to everyone the problem is in WPJM >1.32.3, so why don’t they create a ticket for it and help make a required component work with their theme?

To get search to work(better) again with later versions of WPJM, I added this to /themes/listify-child/functions.php to disable the search form/result caching in ajax-filters.min.js (ajax-filters.js):
-----
// https://github.com/Automattic/WP-Job-Manager/pull/1813
add_filter( 'job_manager_jobs_shortcode_data_attributes', function( $data ) {
  $data['disable-form-state-storage'] = '1';
    return $data;} );
-----

Drawback is that we do not benefit from the caching anymore and the browser back and fw buttons does not work as expected when going back to the search form.
My proposal is to rewrite ajax-filters.js to only restore from the cached latest search/result data when user comes to back to the search/result form using the browser back/fw button. In all other cases, then the URL with any search parameters should be used as cache key, then Theme developers does not have to clear the form/result cache used in ajax-filters.js (clear_state()) when they trigger the search form using an URL with search params.

**Comment by Braehler** [comment] 2019-11-11 09:50
HEy,

we faced the same issue for a while. A work around which we currently are running is to replace the ajax filter of the current stable verison of WPJM with the filter of WPJM 132.3

**Comment by mikeyarce** [comment] 2023-03-01 23:01
Closing this as it's an issue with a Third-Party plugin.

**Closed by mikeyarce** 2023-03-01 23:01 UTC
Labels: Third-party Conflict, Bug
