### ISSUE TITLE
Dropdown to sort by category in wp-admin broken in 1.31.2

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1564] opened 2018-07-31 16:37 UTC
A user in the [forums](https://wordpress.org/support/topic/wp-admin-category-filter-isnt-working-on-1-31-2/#post-10544630) reported the category dropdown for sorting jobs in wp-admin (Job Listings > All Jobs) is broken as of 1.31.2 (or possibly 1.31.1.)

I was able to reproduce. I have an old test site still running 1.31.0, and it works:

<img width="711" alt="cats_wpadmin" src="https://user-images.githubusercontent.com/7585054/43473454-2b2a9a14-94be-11e8-9653-e69c8a771cf5.png">

On my site that is updated to 1.31.2, it isn't working:

<img width="615" alt="nocats" src="https://user-images.githubusercontent.com/7585054/43473513-5d15cd82-94be-11e8-9689-b6bd773a90a4.png">

**Comment by jenhooks** [comment] 2018-07-31 16:45
Reported in 1307300-zen

**Comment by dauand** [comment] 2018-08-28 16:08
Please note it's not just wp-admin. Categories' filter is not showing at all, therefore search via URL /jobs/?search_category=2277 is not working either.

**Comment by jom** [comment] 2018-08-28 16:43
@dauand I'm not able to reproduce issue in `[jobs]` shortcode. Please post a new issue with steps to reproduce with Twenty-Seventeen.

**Comment by dauand** [comment] 2018-08-28 17:07
@jom, this is happening only when the jobs go expired (no active jobs), as it is shown in the screenshot above. Prior to 1.31 (as far as I recall), it was not the case, so now it is not possible to filter old jobs.

**Comment by spencerfinnell** [comment] 2018-11-26 14:08
It's not related to expiration of listings. The output markup is incorrect: https://cloudup.com/cy3yRQ3dZs8

**Comment by jom** [comment] 2018-12-06 14:46
Looks like this was a mixup. It was never marked as fixed in 1.31.3. #1566 was merged post-release for upcoming 1.32.0. It does seem fixed, though.

Let me know if you are still experiencing this issue with `master`.

**Closed by jom** 2018-12-06 14:46 UTC
Labels: [Status] Accepted, [Type] Bug, [Type] Good First Bug
