### ISSUE TITLE
GEO Location error

### ISSUE THREAD

**Issue by Tobekinderopvang** [Automattic/WP-Job-Manager#1005] opened 2017-05-31 12:04 UTC
Hello, 
I just updated today to the new version of WP Job manager. Now my GEO Location does not work anymore. My website is https://tobekinderopvang.nl/vacatures-kinderopvang-nl/

If i search for Haelen no results come up, but my first normal listing is from Haelen. Also my related jobs do not display righ. For the moment it is set on keyword and not on GEO Loaction. Otherwise we do not get results. Please HELP.

Best regards,

Jeroen Pernot

**Comment by jom** [comment] 2017-05-31 12:57
Duplicate of #991.

There is a new setting for Google Maps API Key in WPJM's settings. You can obtain an API key from: https://developers.google.com/maps/documentation/geocoding/get-api-key

For those grandfathered into the use of Google Maps API without a key, a fix will be issued in the next point release that allows you to take advantage of that.

**Closed by jom** 2017-05-31 12:57 UTC

**Comment by Tobekinderopvang** [comment] 2017-05-31 13:22
Jom, 

I already installed the API key, but the problem is still their

**Comment by jom** [comment] 2017-05-31 13:29
Did you enable the Google Maps Geocode API for the API key?

**Comment by VSVS** [comment] 2017-07-06 15:49
@Tobekinderopvang Did you find a fix to your problem?

I've added my key, enabled it and set my referrer to none. Checked the google console and i can see my requests coming in. Checked my plugins and everything is ok and everything is up to date. Is there any where else i can look or what else could be causing this issue?

**Comment by Tobekinderopvang** [comment] 2017-07-06 17:25
Hi,

Yes I fixed the problem. I already mailed you guy's about it.

See attachement.

In the Field Job_location I enabled automatic save to meta data. See 
attachement, although it is in Dutch I think you can find it.


Met inspirerende groet,

Jeroen Pernot

<https://tobekinderopvang.nl/>


T: 06 - 487 689 41
E: info@tobekinderopvang.nl
W:https://www.tobekinderopvang.nl
Op 6-7-2017 om 17:49 schreef Robert Vargas:

**Comment by sapankumarmohanty** [comment] 2018-09-29 00:07
> In the Field Job_location I enabled automatic save to meta data

In the Field Job_location I enabled automatic save to meta data - how did you do that, could you guide me, i am having same issue.

**Comment by sapankumarmohanty** [comment] 2018-09-29 00:14
![image](https://user-images.githubusercontent.com/8361967/46238562-b5fe5200-c3aa-11e8-9817-58580ce5605a.png)

**Comment by cbradigital** [comment] 2019-07-18 10:01
Having the same issue. any solutions so far?

**Comment by cbradigital** [comment] 2019-07-18 10:23
Just found it: installed and activated the additional plugin "WP Job Manager Client-Side Geocoder
" - and now it works after clicking on "geocode address" in the job location field.
