### ISSUE TITLE
New Job Alert Modal Not Working on Some Themes

### ISSUE THREAD

**Issue by Hastibe** [Automattic/WP-Job-Manager#2822] opened 2024-05-14 16:19 UTC
I've reached out to WPJM support via email on April 23, 2024, but they suggested it was an issue with the core WPJM plugin, to post on this GitHub, and then haven't responded to my last email back to them on May 3, 2024 that this doesn't make sense to me, given the issue I'm experiencing being with the Alerts add-on. So, I'm hoping that support can be provided here, after all.

Here's how to replicate the issue:

1. Activate the most recent versions of WP Job Manager and WP Job Manager - Alerts on the most recent version of WordPress core (running on PHP 8.3, in case that makes a difference).

2. Create a page with the [jobs categories="XXX"] shortcode on it, where "XXX" is any category that you've created.

3. Change the theme to [GeneratePress](https://wordpress.org/themes/generatepress/).

4. Click on the "Add alert" link that appears on the page front-end.

5. Instead of the job alerts modal window opening, nothing happens, and this error is generated in the browser console (where "XXX" is your category):

```
job-alerts.js?ver=3.1.1:1 Uncaught TypeError: e.showModal is not a function
    at window.job_manager_alerts.open_add_alert_modal (job-alerts.js?ver=3.1.1:1:569)
    at HTMLAnchorElement.onclick (XXX/:1:20)
window.job_manager_alerts.open_add_alert_modal @ job-alerts.js?ver=3.1.1:1
onclick @ XXX/:1
```

How can I get this addressed between WPJM and GeneratePress?

**Comment by gikaragia** [comment] 2024-05-15 13:02
Hello @Hastibe, I have tried latest WPJM, WPJM Alerts and GeneratePress and couldn't reproduce the issue. [Here is](https://capuchin-of-wrynecks.jurassic.ninja/jobs/) an example test site with the shortcode having the category IT. I can see the 'Add Alert' modal normally. Can you try on a new installation to see if the issue persists?

It seems like the issue is caused by a customization in your environment. I can give you some pointers if you want to debug it. The `showModal` should exist in a dialog element so I am thinking that something modifies your template. I would start by checking that the modal exists in the HTML. To do that you should open the browser tools and search for `jm_add_alert_modal` which is the id of the modal. If this doesn't exist or it isn't a modal it means that something modifies the HTML in your environment and it should be updated. Here is a screenshot of the test site above:
![Screenshot 2024-05-15 at 16 00 07](https://github.com/Automattic/WP-Job-Manager/assets/53191348/dbe00351-8d72-4299-a290-75bb3a0ccdb6)

Other than that I can't offer any more help, unfortunately. I'll close the issue but please re-open if you have clear steps to reproduce this in a new environment.

**Closed as completed by gikaragia** 2024-05-15 13:02 UTC
Labels: Bug

**Comment by Hastibe** [comment] 2024-09-11 23:56
@gikaragia -- just a very belated thanks! Really appreciate you taking the time to look into this and let me know that you actually couldn't reproduce the issue, as that came as a surprise and was helpful to know. 

In case it becomes helpful to know for anyone else, I was still getting the error message even with `jm_add_alert_modal` showing up in HTML, but after switching to a new theme (randomly chose Kadence) and then back to GeneratePress, the issue resolved--I'm not sure what was causing it, nothing should have been cached via plugin or server, but maybe some browser-side caching was not clearing properly and causing this?
