### ISSUE TITLE
Stats: Log searches, search terms

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1513] opened 2018-05-29 15:51 UTC
Suggested in 1190140-zen

It could be useful to site owners to know what kinds of jobs people are looking for on the site. Alternatively, we could add some sort of hook that people can use to build their own logging function, that fires after every search (I looked and didn't see such a hook in https://github.com/Automattic/WP-Job-Manager/blob/fa9347765e51a9b7cb95554dad841ac7b1256504/templates/job-filters.php )

**Comment by gikaragia** [comment] 2023-07-03 12:13
Duplicate of #1733

**Closed by gikaragia** 2023-07-03 12:13 UTC
Labels: [Type] Enhancement
