### ISSUE TITLE
Job Form Going Blank on Submission

### ISSUE THREAD

**Issue by dee987** [Automattic/WP-Job-Manager#2361] opened 2023-01-10 00:10 UTC
**Describe the bug**
When you enter the data, the job form goes blank. 

**To Reproduce**
1.  I can reproduce it with this job - https://docs.google.com/document/d/1QQ5v01pV_Arsct1T_dllSuJDc1Sgs8wV/edit?usp=sharing&ouid=100858400456915097717&rtpof=true&sd=true

On page 2 - there are two paragraphs (supervision and qualifications) :

![image](https://user-images.githubusercontent.com/3209904/211432050-5e554aa4-fab0-452d-a104-82c4a52f5f1f.png)

When I put them individually at: https://floridalibraryjobs.org/ - in the job description field, everything works. When I add them together the page goes blank on submission.  I have tried elimination special characters - and anything else I can think of.  I am not sure what causes the issue.

**Screenshots**

**Expected behavior**
Expect job to post instead the form goes blank.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:   Version | 6.1.1
- WP Job Manager Version: Version **1.39.0**
- PHP Version:   Server architecture | Linux 3.10.0-1160.76.1.el7.x86_64 x86_64
Web server | Apache PHP version | 7.4.33

- Other important details:

**Comment by dee987** [comment] 2023-01-27 16:57
Hi,

We have been having this issue at a greater frequency lately (I have three support tickets opened today).  Is there any movement or ideas on what could be causing the issue?  

Any help would be genuinely appreciated.
Diana

**Comment by dee987** [comment] 2023-01-27 17:17
Hi, this is the error we receive on the console when we attempt to post. 

<img width="1331" alt="Screenshot 2023-01-27 at 12 17 02 PM" src="https://user-images.githubusercontent.com/3209904/215151819-0c4884e2-770f-4433-8661-a0f529d28f36.png">

**Comment by Hastibe** [comment] 2023-02-03 03:49
I just registered an account on your site, so I could see first-hand, and am just waiting for my account to be approved now (mine will be the account registered today at around 10:40pm, using a Gmail address--please don't post the address here, so as to avoid it getting spammed). In the meantime, if you haven't already, I would recommend:

- Using the inspect tool to look at the two paragraphs, once they are pasted in to the form, to see if any odd HTML or characters are showing up at that point.
- Deactivating other plugins and confirming the bug occurs when only WP Job Manager plugin is active.
- Confirming that the bug happens with a default WordPress theme active.

**Comment by Hastibe** [comment] 2023-02-03 03:59
Also, can you replicate the bug on a WP Job Manager demo site ([see here](https://app.instawp.io/launch?t=wp-job-manager-demo))?

**Comment by Hastibe** [comment] 2023-02-03 04:03
Lastly, because there is a 500 internal server error occurring, it would be good to check your server error log (you can ask your host for help with that), and you also might check your WordPress debug log ([see here](https://blog.hubspot.com/website/how-to-set-up-wordpress-error-logs-in-wp-config)) -- just set the debug log to log temporarily, though, as it can be accessed by the public, and could leak information that you wouldn't want.

**Comment by dee987** [comment] 2023-02-03 13:07
Hi,

Hopefully, I approved the right account.


   - We tried - we are not seeing anything specific in the error logs
   - We have looked for a conflict - nothing. I can post on my development
   site without an issue that except for a different host is the same
   settings.
   - Yes, it posts on your demo site

I appreciate your help. I am just stumped and frustrated. We did restart
the server Friday and I am hoping that helps.  Last week, I had three
different people having the issue.

Let me know what you discover.
Diana

**Comment by Hastibe** [comment] 2023-02-03 15:54
Hi Diana,

Yep, you did! Wow, I can understand you being frustrated! Very strange that those two paragraphs trigger the issue, but either paragraph alone doesn't (and that pasting in other multiple paragraphs from the Google doc doesn't trigger it, either). I don't see anything that should be triggering the page to consistently result in that 500 internal server error, when it doesn't for other text.

To try to isolate what section of those two paragraphs is triggering it, I was slowly removing sections of the paragraph to try, and I'd gotten down to this...

```
Provides guidance, advice and assistance to others on work assignments. Provides work direction and serve as a resource for staff. Provides in-depth training and ongoing assistance, instruction and guidance to staff regarding library procedures and protocol.

QUALIFICATIONS

Education and Experience:

Master of Library Science (MLS/MLIS/MIS) degree with a focus on library studies from an American Library Association (ALA) accredited institution, with at least four (4) years post-master’s degree, professional librarian experience required. Public library experience preferred.
```
...when your site went down completely (**EDIT: for just me--my IP address was blocked! I think this may narrow it down, though--details in next post below**), which I wanted to let you know about right away!

If you haven't spoken with your host about this issue (in addition to helping bring the site back up right now), I would definitely do that -- do they have a customer support chat or phone option? Maybe they will see something specific in the error or other server logs / monitors that you haven't? (Once your site is back up, ask them to observe on their end while you generate the 500 internal server error.)

Also, just to double-check, what about the WordPress debug log, was there anything generated in there when the error occurs?

Because it's not occurring on your development site and not occurring on WP Job Manager's demo site, my guess is that it is most likely to be a plugin or theme conflict (if it's not a server security rule or something similar of the host that is for some reason being triggered). You can use the [Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/) plugin to provide a clean WordPress session, where all plugins are disabled, and a default theme is used, but only for your user until you disable it or log out. Then, just enable WP Job Manager, and see if you can still duplicate the result. If you can't, slowly re-enable plugins, until the issue occurs again to identify the plugin causing the problem, and if you enable all of them without problems, then switch to your normal theme to see if that is the cause.

I'll look forward to hearing back!

**Comment by Hastibe** [comment] 2023-02-03 16:06
OH WAIT, your site isn't down. It appears my IP address has been blocked from it. Well, I think that might narrow the issue down! Assuming that the error the paragraphs were generating is what also resulted in my IP address being blocked (due to generating the error multiple times), I think it may be a security plugin conflict or server security rule causing the issue.

**Comment by dee987** [comment] 2023-02-03 18:59
Hi Hastibe,

Are you still showing you're blocked? I am trying to figure out if it's
WordFence or the server but I can't find the IP 134.53.238.41 blocked
anywhere.

I am on with Liquidweb at the moment - we shall see how this goes.
Thank you for looking into this - its just mystifying

Diana

**Comment by Hastibe** [comment] 2023-02-03 19:40
Hi Diana--that's not my IP address, but I am no longer blocked. For Wordfence, while the block was active, it would show-up under Wordfence > Blocking. Speaking of Wordfence, also take a look at Wordfence > Live Traffic, while triggering the issue and see if anything comes up there. 

...Even if nothing does, I would try temporarily disabling Wordfence to see if the issue still occurs while Wordfence is disabled.

**Comment by dee987** [comment] 2023-02-03 20:39
We have a break through.
The modsecurity on the server was blocking on 3000016 - 56 times.
This has a known issue:
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/70

**Comment by Hastibe** [comment] 2023-02-03 21:28
Hurrah! Glad you were able to figure it out (and that is also a ridiculous modsecurity known issue -- so, it must have been hitting on the "select" from "selected" in the first paragraph, and then the "from" in the second paragraph, wow).

**Comment by dee987** [comment] 2023-02-03 21:39
Yes, it is craziness! I went back, and all of the reported issues had those
two words in the description.

**Comment by Hastibe** [comment] 2023-02-03 22:02
Also, Liquidweb should be able to modify the modsecurity rules for your site so that these false hits don't trigger it. If not, I've had a great experience with DreamHost (and I can verify that their modsecurity rules aren't triggered by those two words being entered into a job post!).

**Comment by dee987** [comment] 2023-02-03 22:12
They removed the rule - I could submit the jobs that were stopping us.
I also have one open ticket, so I am waiting to hear if it is resolved for
her.

Thanks for the tip on DreamHost - I will look into it. This is an inherited
server, and I am not so happy with it.

Diana

**Comment by mikeyarce** [comment] 2023-02-24 19:52
Looks like this was resolved so I'm going to close this issue 🎉

**Closed as completed by mikeyarce** 2023-02-24 19:52 UTC
Labels: Bug
