### ISSUE TITLE
Expiry date reduces by one day on editing post

### ISSUE THREAD

**Issue by sanjayjaindc** [Automattic/WP-Job-Manager#872] opened 2017-02-16 16:58 UTC
When you edit the post in any way, for example the Company Description, the post expires one day earlier.

I think this is due to the date decreasing by one day to end the listing at midnight on the previous day. But it should only happen on the first time the job is posted, not on every edit.

**Comment by spencerfinnell** [comment] 2017-02-16 17:05
Duplicate of https://github.com/Automattic/WP-Job-Manager/issues/869

> Dates input remain the same when saving/updating.

**Closed by spencerfinnell** 2017-02-16 17:05 UTC
