### ISSUE TITLE
State and Country are not working now in the latest update 1.38.0

### ISSUE THREAD

**Issue by css1323** [Automattic/WP-Job-Manager#2321] opened 2022-09-06 20:41 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

**Comment by tripflex** [comment] 2022-09-06 20:56
What do you mean "State and Country are not working now in the latest update" ... please be more specific, you also did not fill out any of the details how to replicate this at all.

**Comment by css1323** [comment] 2022-09-06 21:56
[image: image.png]
*This is when i select the location via google autocomplete and it shows
results as 0 results.*


*Actual arizona usa has 48 results as you can see if i disable location
suggestions it shows accurate results.*[image: image.png]

*Just for state only as city is working fine both ways. so please consider
this fixing at the earliest*




*-Best Regards,Shikhar ShahTech Entrepreneur+91-9727069323*


*www.goreadymedia.com
<http://www.goreadymedia.com>Email: ***@***.***
***@***.***>Skype: shikhar.shah*

**Comment by tripflex** [comment] 2022-09-06 23:06
We can not see any images through email, please use a web browser to add images or provide URL to them.  If you're using google autocomplete my guess is you're using my Search and Filtering plugin or some other addon plugin, as that is not native to WP Job Manager, and I suggest that you open a support ticket with that developer.

**Comment by css1323** [comment] 2022-09-07 11:47
tripflex, after the update to 1.38.0 my location started working fine absolutely fine for cities, however when i type in arizona usa where arizona is a state it gives 0 results although there are 48 results under my website jobs. I am using workscout theme and there are no errors in the console too. i request you to please check and update the version with correction for location. 
![image](https://user-images.githubusercontent.com/57360248/188870560-b0f68387-65fb-4bd8-9572-d5ee91861c29.png) This has 27 results those are without zip codes and exact matches after double entering
![image](https://user-images.githubusercontent.com/57360248/188870635-07ac6414-20ed-4e08-b1dc-2227147b0857.png) this are accurate results all results related to arizona. 



Now with google autocomplete on  when i type in state and city it doesnt work. You can try it on turn-to.com for more info. It will show 0 results but on entering without selecting suggestions it will give accurate results. That has happened after this update that is why i am putting up for 1 correction. If you find any issue at my website than i will close this issue as resolved but please atleast check it once.

**Comment by tripflex** [comment] 2022-09-07 13:39
Yeah this is not a bug in the plugin this is the intended functionality, you're using your own custom JavaScript/jQuery for the places auto suggest and it's outputting the `, USA` which is being passed to the search.

You need to strip this from being sent with the `search_location` field as 1.38.0+ will NOT separate location queries into multiple queries separated by commas.

This worked in 1.36 and 1.37 because they merged a very old PR that would turn "Arizona, USA" into two separate queries, which caused all kinds of issues for other users when searching things like "Atlanta, GA" causing it to return incorrect results.

This has been fixed in 1.38.0+ or newer to revert it back to the original handling, more details can be found here:
https://github.com/Automattic/WP-Job-Manager/issues/2287

**Closed as not planned by tripflex** 2022-09-07 13:39 UTC
Labels: [Status] Needs Author Reply

**Comment by css1323** [comment] 2022-09-07 14:27
Cool got it. Thanks a ton for this clarification. I can now enjoy working
on it
