### ISSUE TITLE
Translated Job-category permalink not working when translated (WPML) - 404 Error 

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#688] opened 2016-06-10 12:17 UTC
#### What I Expected To Happen

I run WP Job Manager in three languages using Jobify theme. I use WPML and the .MO-Files to translate the strings. When I click the category link to display all jobs of the category I expect to see all jobs of the category.

EN: /job-category/marketing
DE: de/jobkategorie/marketing-de
FR: fr/categorie-emploi/marketing-fr
#### What Happened Instead

In the English version it works and I get the the job listings displayed. In the DE and FR version I get an 404 page. The slug is correctly translated (see URL above) but the archive is not existing under this URL. Instead I only can access the DE & FR archive via the following links with the base slug in English:

DE: de/**job-category**/marketing-de
FR: fr/**job-category**/marketing-fr

The PO file

`#: includes/class-wp-job-manager-post-types.php:74
msgctxt "Job category slug - resave permalinks after changing this"
msgid "job-category"
msgstr "jobkategorie"`

The code that takes care of the slug
`
/**
         * Taxonomies
         */
        if ( get_option( 'job_manager_enable_categories' ) ) {
            $singular  = __( 'Job category', 'wp-job-manager' );
            $plural    = __( 'Job categories', 'wp-job-manager' );
            if ( current_theme_supports( 'job-manager-templates' ) ) {
                $rewrite   = array(
                    'slug'         => _x( 'job-category', 'Job category slug - resave permalinks after changing this', 'wp-job-manager' ),
                    'with_front'   => false,
                    'hierarchical' => false
                );
                $public    = true;
            } else {
                $rewrite   = false;
                $public    = false;
            }
`

When accessing the English correctly working archive I noticed that the hreflang-URLs in page header are also wrong:

**What is displayed:**
`
<link rel="alternate" hreflang="en-US" href="http://example.com/job-category/retail/" />
<link rel="alternate" hreflang="fr-FR" href="http://example.com/fr/job-category/vente-au-detail/" />
<link rel="alternate" hreflang="de-DE" href="http://example.com/de/job-category/einzelhandel/" />`

**What should be displayed**

`<link rel="alternate" hreflang="en-US" href="http://example.com/job-category/retail/" />
<link rel="alternate" hreflang="fr-FR" href="http://example.com/fr/categorie-emploi/vente-au-detail/" />
<link rel="alternate" hreflang="de-DE" href="http://example.com/de/jobkategorie/einzelhandel/" />`
#### Steps to Reproduce the Bug

Job Manager + WPML + Jobify or other theme that supports job-manager-templates

**Comment by chaselivingston** [comment] 2016-08-05 19:48
@Lens40 This sounds like a duplicate of #692. Could you confirm?

**Comment by Lens40** [comment] 2016-08-05 20:58
Hi Chase, might be. I will check the fix in #692 and let you know if it solves the issue.

**Comment by Lens40** [comment] 2016-10-12 17:52
Hi Chase, sorry for my late feedback, unfortunately the mentioned fix does not fix my issue.

**Comment by donnchawp** [comment] 2016-10-14 12:57
I don't have access to the WPML plugin. Did you translate the slugs as described [here](https://wpml.org/documentation/getting-started-guide/translating-page-slugs/)?

**Comment by praitosola** [comment] 2016-10-16 09:12
We have the same problem. Seems that Job Manager does not support WPML option: "Different languages in directories", for us only works if "Language name added as a parameter". We are using Job Manager with the theme Listable.

**Comment by donnchawp** [comment] 2016-10-17 12:32
Have you both tried to get [support](https://wpml.org/forums/forum/english-support/) from the WPML developers? They may be able to advise you on how the fix the problem.

**Comment by Lens40** [comment] 2016-10-17 16:00
Hey Don, 
yes I did and they said its the plugins fault :( - https://wpml.org/de/forums/topic/wp-job-manager-permalink-korrekt-aber-404-fehler/ (German)

**Comment by praitosola** [comment] 2016-10-17 16:18
Hi My programmer says the problem is different, (though this issue on the thread could be problem too).

It is not about permalinks

Our problem is that Job Manager does not support language URL in the directories ( but we do not know if this is Listable error or Job manager)

**Comment by donnchawp** [comment] 2016-10-17 16:38
OK, I have requested help from the WPML developers, but I would appreciate any advice you or your developers can give us. 
What do you mean by "language URL in the directories"? How do you support more than one language?
The PO file has the translation for job-category, but what is wrong with that?

Can you give me an example of a plugin that uses post types or similar that has been modified to work with WPML?

**Comment by Lens40** [comment] 2016-10-17 16:53
Hi Don, I can only give you my feedback for my issue as I guess the issue from praitosola might be something different, at least I do not get it so far. 

In my case the translation via PO-File works great. The URLs are also generated as they should, the only issue is that when you open these translated URLs you get an 404 error. So the correct URL is not pointing to the correct content when running a multilangual site. 


Wp job Manager itselfs uses the job custom post type with WPML which works all right but the category URLs are not a post type if I am right and that seems to be part of the issue. Maybe its also related to my latest issue #786. I guess WPML would be happy to help.

**Comment by praitosola** [comment] 2016-10-17 16:56
Hi,

Many thanks. I will give you more detailed information from my programmer tomorrow. - He has gone for the day. 

I can also send you link to the site we are developing, so you see what happens.

Best regards,
Pauliina

**Comment by donnchawp** [comment] 2016-10-21 11:15
@Lens40 - if you apply the code from #786 - the bit that adds the wpml_job_id does it fix this issue?

**Comment by Lens40** [comment] 2016-10-25 20:16
Indeed the 404-Errors are gone and it works when using the links in the job descriptions! But there is one thing that is not working -> the WPML Language-Switcher-URL pointing to the other language versions is using a wrong URL and the href-lang-Tags on the category-pages are also wrong. Depending on the language I am using these URLs are always build with the slug of the current language:

e.g. English Version:
link rel="alternate" hreflang="en-GB" href="example.com/job-category/marketing **ok**
link rel="alternate" hreflang="fr-FR" href="example.com/**job-category**/markting-fr (wrong should be "categorie-emploi")
link rel="alternate" hreflang="de-DE" href=" example.com/**job-category**/markting-de (wrong should be "jobkategorie")

e.g. French version:
link rel="alternate" hreflang="en-GB" href="example.com/**categorie-emploi**/marketing (wrong should be "job-category")
link rel="alternate" hreflang="fr-FR" href="example.com/categorie-emploi/markting-fr **OK**
link rel="alternate" hreflang="de-DE" href=" example.com/**categorie-emploi**/markting-de (wrong should be "jobkategorie")

What should they look like:
link rel="alternate" hreflang="en-GB" href="example.com/**job-category**/marketing 
link rel="alternate" hreflang="fr-FR" href="example.com/**categorie-emploi**/markting-fr
link rel="alternate" hreflang="de-DE" href=" example.com/**jobkategorie**/markting-de

The language switcher is behaving the same way as the tags above. Means that if I am on the french version it will always use the french slug to build the other language URLs etc.

**Comment by donnchawp** [comment] 2016-10-26 12:45
I wonder if that's similar to the problem reported here: https://github.com/Automattic/WP-Job-Manager/issues/692 ?

**Comment by Lens40** [comment] 2016-10-26 13:00
Hmm I guess not in the current case your modification works perfectly as it should. Within the language version you can perfectly access the category pages via the slug you have set in the language file. This wasn't the case before. Before the URL was right but the output was a 404 page. So currently only WPML language switcher is ignoring it and generates a wrong URL using the current page slug which unfortunately is different between the languages and the hreflang-tags are wrongly build. But this wrong behaviour was already there before your modification see first post.

**Comment by praitosola** [comment] 2016-10-26 15:41
Hi,

I think I did not sen you the link to our site in development.

Here is it:
http://dftest.pauliina.com/

English works fine. And FI (Finnish as well) - but German and Russian do not work.

The listable people are checking this as well.

Best regards,
Pauliina

**Comment by Lens40** [comment] 2016-11-27 11:45
@donnchawp have you found a solutions for the language switcher and the hreflang? As your modifications fixes the main issue of the 404 pages and also fixes an issue with the duplicate job function which is not working with WPML without your code i would definitely add it to the next release even if the language switcher and hreflangtag is not fixed.

**Comment by praitosola** [comment] 2016-11-27 11:52
Many thanks - so this is for this new issue:

Hi Ali,

What update fixed the problem we had. Many thanks!

We would have another little issue though. 

1) I am trying to copy and paste in Home Page “highlighted categories” the other languages translations. How ever, after saving it just shows the english slugs and text there.

Please see the image attached.

Also it is quite hard to control all widgets on the home page in all languages. 


Also you can see the EN and FI home pages here (not live site yet):
http://dftest.pauliina.com/ <http://dftest.pauliina.com/>
http://dftest.pauliina.com/fi/ <http://dftest.pauliina.com/fi/>

Best regards,
Pauliina

**Comment by Lens40** [comment] 2016-11-27 11:56
@praitosola could you please open a new Issue instead of hijacking this one with unrelated problems? Thank you!

**Comment by praitosola** [comment] 2016-11-27 12:00
Ok!

**Comment by annezazuu** [comment] 2017-02-14 23:31
Also brought up here 3030178-t

**Comment by bikedorkjon** [comment] 2017-02-15 23:17
Seen in 3061941-t

**Comment by eppul** [comment] 2017-03-08 06:54
So what is the situation. The due date for this update was 13 days ago.

**Comment by eppul** [comment] 2017-03-09 07:55
Well that was lame.

**Comment by annezazu** [comment] 2017-06-17 00:54
The user in 3267822-t also notes that tags are not translating using WPML cc @davoraltman

**Closed** 2017-06-22 16:01 UTC
Labels: in progress, [Pri] Normal, [Status] Has PR, [Type] Bug
