### ISSUE TITLE
"Apply for Job" button on front-end -- mailto subject quotes around job title not encoded properly

### ISSUE THREAD

**Issue by thadbloom** [Automattic/WP-Job-Manager#1653] opened 2019-01-09 16:57 UTC
#### Steps to Reproduce
1. Navigate to job where email is the method for applying
2. Click on "Apply for job"
3. Click on the email address

#### What I Expected
Email subject to be populated correctly

#### What Happened Instead
When clicking on the "Apply for Job" button when viewing a single job post, if there is an email address the subject is already populated ie: "Re: Application via &quot;DAS Supervisor&quot; listing on https://blahblah.com".

This is great, however when this link opens in Apple Mail and Outlook -- the quotes around the title are not encoded, ie:

`Re: Application via &quot;DAS Supervisor&quot; listing on https://blahblah.com`

#### WordPress / WP Job Manager Version
5.02 / 1.31.3

#### Browser / OS Version
Chrome / macOS Mojave

**Comment by jom** [comment] 2019-12-05 14:29
Duplicate of #1605 ; Fixed in #1606

**Closed by jom** 2019-12-05 14:29 UTC

**Comment by CarlitoDevDreamer** [comment] 2022-11-25 22:23
Is there a way to only allow logged users to have access to the content of the "Apply for job" button?
