### ISSUE TITLE
Can't purchase job subscription package from product page

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#950] opened 2017-05-04 10:50 UTC
#### Steps to Reproduce the Bug

1. Create a Job Subscription Package product
2. Give it a price and select monthly or yearly.
3. Publish the product
4. View the product page

#### What I Expected To Happen

Price would display along with an "Add to cart" button.

#### What Happened Instead

Price displays as:

![image](https://cloud.githubusercontent.com/assets/1990037/25700481/d3d9527c-30bf-11e7-8c05-24e898f0587e.png)

and there is no Add to Cart button.

**Comment by jom** [comment] 2017-05-15 15:55
I'm not able to reproduce the `/ Array` part. Which version of WooCommerce / woocommerce-subscriptions? Is there a ticket associated with this? If so, let's create an issue in the plugin repo.

As far as I can tell, we never add an 'Add to Cart' button for job package subscription products. I'm not sure why we don't, but in `WC_Paid_Listings_Cart` it is just added for `job_package` product type. To add this for subscriptions, we would need to add this:
```add_action( 'woocommerce_job_package_subscription_add_to_cart', 'WC_Subscriptions::subscription_add_to_cart', 30 );```

Closing for issue in the plugin repo.

**Closed by jom** 2017-05-15 15:55 UTC
Labels: [Type] Plugin Issue

**Comment by danjjohnson** [comment] 2017-05-16 11:36
Updated WC and Subs and no longer seeing the / Array issue either :)

Will open an issue for the add to cart button in the add-on repo

**Comment by aheckler** [comment] 2017-05-16 18:05
3215379-t
