### ISSUE TITLE
Category link in WP-Admin job listings is not filtering posts

### ISSUE THREAD

**Issue by bindlegirl** [Automattic/WP-Job-Manager#2131] opened 2021-03-10 10:23 UTC
Job listings in WP-Admin have a category link that should be working as a category filter. Instead, the link loads the site home page. 

It seems that the category link is missing the `wp-admin/edit.php` part so instead of `https://domain.com/wp-admin/edit.php?job_listing_category=category` it has this link `https://domain.com/?job_listing_category=category`

**Comment by alexsanford** [comment] 2021-08-20 18:17
Actually, clicking on this link shows the _frontend_ archive page for the category, which I imagine was the intended behaviour. I agree that it's not super-intuitive, though.

In any case, I don't think this is a bug. I'll close this, but feel free to submit an enhancement request for changing those links if you would like.

**Closed by alexsanford** 2021-08-20 18:17 UTC
Labels: [Type] Bug
