### ISSUE TITLE
Unwanted Image Placeholder Showing up on top of Listings

### ISSUE THREAD

**Issue by JohnCallanan** [Automattic/WP-Job-Manager#2677] opened 2023-12-11 17:25 UTC
**Describe the bug**
We are seeing a random placeholder image appearing on top of the listings pages. see the screenshot:

https://tinyurl.com/yst5ddav

Looking at the page inspector, the image class is "company_logo" even though we have not added a logo to the listings. the image source is https://prbany.com/wp-content/plugins/wp-job-manager/assets/images/company.png. This appears to be showing on all of the job listings.

**To Reproduce**
1. Go to 'https://prbany.com/job/senior-staff-attorney-sanctuary-for-families/'
2. See the placeholder image covering the content

**Screenshots**
https://tinyurl.com/yst5ddav

**Expected behavior**
The listings were showing up fine and without this image on top until just a few days ago.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.4.2
- WP Job Manager Version:2.1.1
- PHP Version: 8.2
- Other important details:

**Comment by mikeyarce** [comment] 2024-01-13 21:38
@JohnCallanan - this sounds more like a theme problem than a problem with WP Job Manager.  I can't reproduce on a default theme.  I'll close this for now, but if you can reproduce this on a default theme with no other plugins active, please let us know!

**Closed as completed by mikeyarce** 2024-01-13 21:38 UTC
Labels: Bug
