### ISSUE TITLE
WP-Job-Manager no longer in WP Admin Menu nor displaying active jobs (after update of Job Manager)

### ISSUE THREAD

**Issue by glennphillips** [Automattic/WP-Job-Manager#1931] opened 2019-11-06 16:01 UTC
#### Steps to Reproduce
1. Install update 1.34.1 from older version
2. WP Job Manager no longer appears in the WP menu, no way to access jobs, WP Page with [Jobs] no longer shows any of the active jobs, unable to access/view/edit jobs.
3.

#### What I Expected
WP Job Manager options to continue appearing in the menu.

#### What Happened Instead
WP Job Manager no longer appears in the WP menu.

#### WordPress / WP Job Manager Version
WP 5.2.4 / 1.34.1

#### Browser / OS Version
Chrome, latest.

**Comment by jom** [comment] 2019-11-06 16:26
Do you recall what version you came from? Try deactivating and reactivating (don't uninstall).

**Comment by glennphillips** [comment] 2019-11-06 16:42
I don’t recall prior version, but we update plugins every month or two, so it would not have been too old.

 

I did deactivate and reactivate…. 4 times.

 

Hope that helps.

Thanks!
G

**Comment by jom** [comment] 2019-11-06 16:57
Can you contact us on https://wpjobmanager.com/contact/ and reference this issue? We'd like to take a look. I unable to reproduce and we haven't had other reports so far.

**Comment by glennphillips** [comment] 2019-11-06 17:45
To be sure I understand… you want me to just describe the issue on the presales form?

 

Thanks!
G

**Comment by jom** [comment] 2019-11-06 18:54
Yes, or just reference this issue. It'll get you into our support ticketing system.

My guess there is a third-party conflict happening. We still haven't had any other reports so far.

**Comment by jom** [comment] 2019-11-08 12:14
Closing for now until we have reproducible steps from a fresh install.

**Closed by jom** 2019-11-08 12:14 UTC
