### ISSUE TITLE
PHP8.x PHP Warning: Undefined property: WP_Error::$name in

### ISSUE THREAD

**Issue by a-riddle-fan** [Automattic/WP-Job-Manager#2347] opened 2022-12-12 09:54 UTC
If I use the WP-Job-Manager on Wordpress 6.0.3 and WP Job Manager Version 1.38.1 

**I got the Error-Report:**
_AH01071: Got error 'PHP message: PHP Warning: Undefined property: WP_Error::$name in [/path/wp-content/plugins/wp-job-manager-locations/wp-job-manager-locations.php] on line 328', referer: https://URL/Page/_

Here is the CodePart (Line 328 is bold):
```
   /**
     * Filter the AJAX to update the "showing" text.
     */
    public function custom_filter_text( $text ) {
        $params = array();

        parse_str( $_REQUEST[ 'form_data' ], $params );

        $term = get_term( $params[ 'search_region' ], 'job_listing_region' );

        **$text .= sprintf( ' ' .  __( 'in %s', 'wp-job-manager-locations' ) . ' ', $term->name );**

        return $text;
    }
```

What must I do to fix this Issue?

**Comment by a-riddle-fan** [comment] 2022-12-16 06:37
do you need more Information? 
The PHP Logfile means that the line:
`$text .= sprintf( ' ' .  __( 'in %s', 'wp-job-manager-locations' ) . ' ', $term->name );`
is the reason for the issue. 

I want to use PHP 8.1 with this WordPress Plugin.

**Comment by mikeyarce** [comment] 2023-01-12 18:55
This might just be a problem with your site and not with the plugin.  Can you give us specific steps so we can reproduce this on a test site?   If it's just a problem with your site, you can get support here: https://wpjobmanager.com/support/

**Comment by Gnodesign** [comment] 2023-01-14 14:19
@adminquest The issue comes from the [WPJM Regions](https://wordpress.org/plugins/wp-job-manager-locations/) plugin.

**Comment by mikeyarce** [comment] 2023-01-15 19:15
Thanks @Gnodesign for that info - going to close this out since it's not an issue with the WPJM plugin.

**Closed as completed by mikeyarce** 2023-01-15 19:15 UTC
Labels: [Status] Needs Author Reply, Bug

**Comment by a-riddle-fan** [comment] 2023-02-14 14:43
Thanks a lot for this Help!
