### ISSUE TITLE
Disable "Submit Listing" Button After Initial Click

### ISSUE THREAD

**Issue by Irpe1337master** [Automattic/WP-Job-Manager#863] opened 2017-01-30 08:17 UTC
I have WP job manager, WooCommerce and WP Job Manager Paid Listings plugin installed.  

When I'm at the listing preview stage and click "submit listing" button multiple times. 
![submit lsiting](https://cloud.githubusercontent.com/assets/25027233/22416065/8dbb98c0-e6d4-11e6-8d91-47d6d6c9cec8.png)

Selected job package product is added to cart multiple times which gives errors.
![multiple purchases](https://cloud.githubusercontent.com/assets/25027233/22416066/918f327c-e6d4-11e6-8ed7-044e104b0752.png)

Steps to Reproduce the Bug:
 -Select Job Package
 -Fill necessary listing info
 -Preview listing
 -Press "submit listing" button multiple times
 -Checkout page gives errors.

**Comment by davoraltman** [comment] 2017-06-04 14:42
@Irpe1337master I can't reproduce this with the latest version of WP job manager, WooCommerce, and WP Job Manager Paid Listings plugins. Can you check again and let me know if the issue is still there?

**Comment by Irpe1337master** [comment] 2017-06-13 05:52
Hey, currently it is not possible for me to update one of the plugins so I'm not able to test this atm. Sorry.

**Comment by jom** [comment] 2017-06-13 08:35
Closing for now. Let us know if you're able to reproduce this with current versions.

**Closed by jom** 2017-06-13 08:35 UTC
Labels: [Pri] Normal, Enhancement

**Comment by Hastibe** [comment] 2019-09-28 17:00
@jom, I can confirm that this is still an issue with the latest version of WP Job Manager, WooCommerce, and WC Paid Listings. I can replicate it on my site, and it can be replicated on the [WC PL Demo](https://demo-wcpl.wpjobmanager.com/) site:

![Cart errors](https://user-images.githubusercontent.com/50286801/65819883-633abe80-e1e7-11e9-8e39-51f33ad075f7.png)

@Irpe1337master - did you ever figure out a solution, independently?

**Comment by Irpe1337master** [comment] 2019-09-28 20:29
@Hastibe if I remember correctly I didn't try to fix this on my own. 

A quick (_maybe a little bit dirty_) fix could be disabling "submit listing" button using javascript after user clicks the button. This is a just a suggestion and not tested :)
