### ISSUE TITLE
Credit balance unchanged after manually creating new order and job listing

### ISSUE THREAD

**Issue by okbk** [Automattic/WP-Job-Manager#1196] opened 2017-10-04 14:09 UTC
If you assign a package to someone in the admin by using 'add order'.

Then, you create a new job listing and assign it to that user. I would expect to then be able to 'use' a credit if the user has one. 

Instead, it's just assigned to the user (correctly) but if the user logs in, they can clearly see that their credit balance remains unchanged.

**Comment by jom** [comment] 2017-10-16 15:15
This is an enhancement request (transfer job listings to different packages/users) with WC Paid Listings. We're tracking it for that paid add-on. This is just for WPJM core issues.

Duplicate of #737

**Closed by jom** 2017-10-16 15:15 UTC
Labels: [Type] Plugin Issue
