### ISSUE TITLE
Company profile

### ISSUE THREAD

**Issue by TheJobWork** [Automattic/WP-Job-Manager#1827] opened 2019-07-23 23:25 UTC
I am interested in the Add ons bundle of WP job manager to use with Buddy Press, however i dont see any company profile...

In 2020 online recruitment expectations have changed and extended company profile with: reviews, salary surveys, endorsement ...are crucial.

**Comment by Hastibe** [comment] 2019-07-27 05:40
There are several add-ons that provide limited company profiles of sorts, but they are all buggy, mostly or completely unsupported, or just broken. I strongly second what @TheJobWork says about robust company profiles being an expectation on job websites--it is our most requested feature by both employers and job seekers.

**Comment by thedigitalcircle** [comment] 2019-07-27 13:37
Hi
I also agree with that. I think Smyles already have worked with a new company profile. 
I am desparately waiting for that.
Shuvashish

**Comment by TheJobWork** [comment] 2019-07-27 14:42
Its hard to even conceive a job board plug in without it, i still not get it, unless they started WP job manager from a simple job posting plug in as they used to do back i the days, but we are talking of 15 years ago.

**Comment by AmineBAIK1** [comment] 2019-07-29 15:50
I was wondering the same, and i strongly join the idea to add companies profiles to WP-JobManager

**Comment by richardmtl** [comment] 2019-07-29 18:51
Duplicate of https://github.com/Automattic/WP-Job-Manager/issues/1086

**Closed by richardmtl** 2019-07-29 18:51 UTC

**Comment by TheJobWork** [comment] 2019-07-29 19:05
does this mean since 2017 july this core feature was not even considered and started ?

**Comment by richardmtl** [comment] 2019-07-29 19:07
Correct. There are a few plugins out there that do something similar, but we have no added it to the plugin and it is not on our current immediate roadmap, @TheJobWork.

**Comment by tripflex** [comment] 2019-07-29 19:52
After being contacted by over 10 clients requesting me to build a custom one -- I've started working on an add-on for this so it functions similar to the way Resumes addon works, allowing to select existing companies via submit form and so on.  The few plugins out there that are available for Companies seem to be inadequate and i hope to be able to release it to general public within the next month.

**Comment by TheJobWork** [comment] 2019-07-29 23:43
None of the plugins present on the third party pages are well functionning, sadly, We wished that WP job manager certified their vendors. 

At my great surprise i just saw that company profile, a core element was not in the paid addson version. What a disapointment; but still have a few days to think about keeping it or be refunded luckily.

**Comment by TheJobWork** [comment] 2019-07-29 23:45
> After being contacted by over 10 clients requesting me to build a custom one -- I've started working on an add-on for this so it functions similar to the way Resumes addon works, allowing to select existing companies via submit form and so on. The few plugins out there that are available for Companies seem to be inadequate and i hope to be able to release it to general public within the next month.

Good news, dont forget company reviews and employees as well as salary surveys, its a 2020 trend.

**Comment by joblux** [comment] 2019-09-10 04:10
lots of talks and little actions , addson fromWP job manager havent been updated for ....years...this is not acceptabel for paid addons.
