### ISSUE TITLE
Feature Request: Auto Approve by User Role

### ISSUE THREAD

**Issue by turtlepod** [Automattic/WP-Job-Manager#1159] opened 2017-08-24 13:30 UTC
Currently we only able to auto-approve/moderate listing submission.
I think it's a good idea to able to auto-approve (maybe by user role)?

**Comment by jom** [comment] 2017-09-19 23:11
Duplicate of #933

Feel free to add on to that discussion about user role.

**Closed by jom** 2017-09-19 23:11 UTC
