### ISSUE TITLE
Job Titles/Post Titles Disappear after Job Expires

### ISSUE THREAD

**Issue by mikeidea** [Automattic/WP-Job-Manager#1128] opened 2017-07-28 15:28 UTC
#### What I Expected To Happen
I expected the job title to remain after it had past its set expiration time.

#### What Happened Instead
The job title/post title removes itself post expiration.

#### Steps to Reproduce the Bug
Create a job, set an expiration date, let that time pass and review post in WP.

**Comment by jom** [comment] 2017-11-22 12:24
I'm not able to reproduce this. I don't see anything in the code that touches that field upon expiration. I'm closing this for now, but if you're still experiencing this try to reproduce with an instance with just a default theme and WPJM by itself.

**Closed by jom** 2017-11-22 12:24 UTC
