### ISSUE TITLE
UTF-8 Characters Being Stripped From City Name

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#662] opened 2016-04-26 15:17 UTC
What I Expected To Happen: The "ã" in São Paulo to display properly.

What Happened Instead: The ã is being stripped and the city name is displaying as "So Paulo". Screenshot of the problem: http://d.pr/i/WhuI

Steps to Reproduce the Bug: Load the page at http://www.itatibando.com.br/ and scroll down to the Recently Added section.

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-geocode.php#L193

**Comment by jenhooks** [comment] 2016-04-26 15:17
Relevant ticket: #2641907-t

**Comment by turtlepod** [comment] 2017-03-27 00:54
I tested this in my local install and i can;t reproduce the issue.
I checked your site and it seem to be working as expected.

Is this issue resolved?

![wpjm-662-utf8-city-name](https://cloud.githubusercontent.com/assets/1705549/24337047/94b916c4-12c2-11e7-9e79-5af4910b524b.png)

**Comment by dbtlr** [comment] 2017-03-27 01:24
This may have been an issue with the `sanitize_text_field()` function in WordPress Core, since that is the function that would have been stripping this. Since I can no longer reproduce this issue, I'm going to close this. My best guess is that this was a Core bug that has been since fixed.

**Closed** 2017-04-05 22:08 UTC
Labels: [Pri] High, Bug
