### ISSUE TITLE
Listing Expiry Date field going to current date when using Safari

### ISSUE THREAD

**Issue by raduconst** [Automattic/WP-Job-Manager#1054] opened 2017-06-23 13:29 UTC
#### What I Expected To Happen
I just want to edit the Listing Expiry Date of a listing from the dashboard area
#### What Happened Instead
The date from the Listing Expiry Date field gets the current date when trying to edit the date
#### Steps to Reproduce the Bug
1. Add a listing through the front-end;
2. Go to dashboard area;
3. Approve the listing you just created;
4. Edit the listing through the dashboard area;
5. Change the expire date (let's say, add a few more days);
6. Hit the Update button;
7. Once the page refreshes, the Listing Expiry Date field has the current date value on it;
8. [bonus] If you go to the All Listings area, you can see that the expiry date is the one that you set, not the current date.
This only happens in Safari. Chrome and Firefox work as intended.

**Comment by spencerfinnell** [comment] 2017-06-23 13:40
Can you confirm you are using version 1.26.2 of the plugin?

**Comment by raduconst** [comment] 2017-06-23 13:49
@spencerfinnell Yes, I checked both 1.26.1 and 1.26.2

**Comment by spencerfinnell** [comment] 2017-06-23 14:04
Can't reproduce personally. Should have been fixed in https://github.com/Automattic/WP-Job-Manager/pull/903 https://github.com/Automattic/WP-Job-Manager/pull/1013 https://github.com/Automattic/WP-Job-Manager/pull/1008

Is your site language set to anything besides English? Are you using the date picker to change the date? Does it happen if you add a listing through the dashboard?

**Comment by konradwww** [comment] 2017-06-26 09:42
I can reproduce this bug on Safari 10.1.1. Language English,  jobs added from the admin dashboard. It seems like the Datepicker always has the current date set.

**Comment by jom** [comment] 2017-07-06 08:58
I can reproduce. Working on a fix.

**Closed** 2017-07-06 10:05 UTC
Labels: [Type] Bug
