### ISSUE TITLE
error on add job preview

### ISSUE THREAD

**Issue by dariliya** [Automattic/WP-Job-Manager#884] opened 2017-03-02 16:46 UTC
I get this error on job preview: 
Notice: Array to string conversion in /home/dariliya/public_html/najdi-zaposlitev/wp-content/plugins/wp-job-manager/includes/forms/class-wp-job-manager-form-submit-job.php on line 520

Any idea what I have to do to solve this?
Br

**Comment by tripflex** [comment] 2017-03-08 21:53
dupe of #854 

You should disable PHP warning output to prevent it from showing on your site https://aristath.github.io/blog/wp-hide-php-errors

**Closed by tripflex** 2017-03-08 21:53 UTC

**Comment by dariliya** [comment] 2017-03-09 13:49
I did that and it was not visible then. But after last update (today) it works fine even if I set debug on true. Problem solved. Thank you! :+1:
