### ISSUE TITLE
Possible multiple status changes during job submission

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#731] opened 2016-08-03 14:30 UTC
Reported via the forums:

Post Status Notifier recorded the following state changes during the job submission process

Preview –to- pending payment (multiple times per posting – limiting does not fix notifications)
Pending payment –to- pending (multiple times per posting - limiting does not fix notifications)
New –to- preview (only one – but using would mean that employer got notification before job submitted, or if they previewed and did not submit)

More details here:
https://wordpress.org/support/topic/post-status-notifier-logged-duplicates-of-events?replies=1

**Comment by donnchawp** [comment] 2016-10-06 09:16
I couldn't replicate this using the transition_post_status filter. It showed one transition for each stage when I dumped it to a file:

> post status: 39 from new to preview
> post status: 39 from preview to pending
> post status: 39 from pending to publish

I'll check how Post Status Notifier does it.

**Comment by turtlepod** [comment] 2017-03-27 06:31
I can't replicate this too.
Tested using https://wordpress.org/plugins/post-status-notifier-lite/

On job submission if I edit my submission,
I did get notification of status changed from "preview" to "preview" (which is weird, because it's the same status). But I think that's the Post Status Notifier Lite issue of reporting the same status (?)

On paid listing, it seem to only send notification once too. from "pending payment" to "publish" after order cleared.

Is it possible that you have multiple Post Status Notifier Rules that cause this multiple notification?

**Comment by tripflex** [comment] 2017-03-28 17:33
Yeah this is probably specific to the user's site, or a bug with the plugin you're using.  

I say that because my emails addon for WPJM uses post status to send emails, so if there was a bug like this in core, I would know about it because I would have tons of clients complaining about duplicate emails being sent.

**Comment by bikedorkjon** [comment] 2017-04-05 22:11
Since there are no more reports of this and it's not reproducible I'm closing

**Closed by bikedorkjon** 2017-04-05 22:11 UTC
Labels: [Pri] High, Bug
