### ISSUE TITLE
WP Job Manager jobs listing does not show on WPML page when filters are set to true 

### ISSUE THREAD

**Issue by karinorage** [Automattic/WP-Job-Manager#1197] opened 2017-10-05 08:23 UTC
I use wp job manager and WPML.
The default page shows the jobslisting (shortcode [jobs]) on http://www.mysite.eu/ perfectly

But on the translated page http://www.mysite.eu/en/ it shows only a loader icon and is not giving results
The shortcode [jobs] has default the filters set to true.
When I add to the shortcode [jobs] the following [jobs show_filters="false"] the listing shows, but of course without the filters.

**Comment by jom** [comment] 2017-10-05 09:53
Duplicate of #1176. WPML is working on a fix.

**Closed by jom** 2017-10-05 09:53 UTC

**Comment by spencerfinnell** [comment] 2017-10-05 13:21
@jom Have a link to any public tracking on the WPML side? Would be nice to have something to refer customers to.

**Comment by jom** [comment] 2017-10-05 13:53
Not that I know of. I talked to @vukvukovich yesterday. It looks like it has something to do with using `relative` for the `$scheme` in `home_url()`. It looks like the original purpose of using `relative` when forming the AJAX request endpoint was for mixed HTTP/HTTPS WP instances. It looks like WP does some sniffing for which scheme to use when not specified. I'm not sure if it has gotten better at it than when this was originally implemented.

**Comment by karinorage** [comment] 2017-10-08 08:33
WPML returned the following workaround: [https://wpml.org/forums/topic/wp-job-manager-jobslisting-shows-only-on-default-language-page/](url)

**Comment by vukvukovich** [comment] 2017-10-17 12:40
Hi all,

This one is fixed in the upcoming WPML version.

Cheers!
