### ISSUE TITLE
Specify missing field in "Please fill out this field" message

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/WP-Job-Manager#1158] opened 2017-08-24 09:07 UTC
When you try to submit a job without completing all the required fields you get a popup saying "Please fill out this field" but it doesn't say which field and it points to a position that is offscreen and cannot be seen.

![jobs](https://user-images.githubusercontent.com/7946521/29658724-e0421516-88b3-11e7-9958-9b49dfad25ff.png)

Ticket: 648371-zen

**Comment by donnapep** [comment] 2017-08-28 15:21
Could you add some details about OS and browser versions? I'm unable to reproduce on Mac 10.12.6 Chrome 60.0.3112.101. Also, that tooltip that pops up is browser functionality, not functionality that WP Job Manager adds, so this may actually be a browser issue.

**Comment by rachelsquirrel** [comment] 2017-08-28 16:30
I use Opera 47.0 and Mac 10.11.16.

I'm not sure which browser the user is using but I'll check. In the meantime a screenshot of their browser is here (I think it's Windows and IE):

https://i.imgur.com/5VOEPQ6.png

I have a similar problem when I use Chrome. It works fine with Safari.

**Comment by donnapep** [comment] 2017-08-28 20:32
Thanks! I'd like to try to reproduce this in Chrome but haven't had any luck so far. Perhaps it's theme-related. Which theme are you using that shows the issue?

**Comment by donnapep** [comment] 2017-08-28 21:48
Ah, excellent. I can reproduce on the [WPJM demo site](https://demo.wpjobmanager.com/post-a-job/).

**Comment by donnapep** [comment] 2017-08-28 22:10
This only happens in themes with a fixed header. When an element is marked as `required`, the browser scrolls up to the first required field and shows the tooltip over it. However, in the case of fixed positioning, the end result is that the required field is hidden beneath the header.

It's possible to override the browser's default behaviour for required fields, but I don't think we should bother. It's probably better to roll our own validation UI and not rely on the browser for that.

**Comment by donnapep** [comment] 2017-08-30 14:13
Closing this issue in favour of t[his one](https://github.com/Automattic/jpop-issues/issues/949).

**Closed by donnapep** 2017-08-30 14:13 UTC
Labels: [Type] Bug

**Comment by spencerfinnell** [comment] 2017-08-30 14:47
@donnapep 404? Related: #842

**Comment by donnapep** [comment] 2017-08-30 19:31
@spencerfinnell Yeah, sorry. That's one in a private repo for organizational purposes. It's essentially an issue to track possibly improving the UI for client-side validation.

**Comment by tripflex** [comment] 2017-09-07 15:35
Just an FYI too, if someone is using the Field Editor plugin they can disable the required attribute from being added to fields by disabling it in the Field Editor Settings page.
