### ISSUE TITLE
Select2 not working on Job submission form with Ultimate Member active

### ISSUE THREAD

**Issue by XTard** [Automattic/WP-Job-Manager#2316] opened 2022-08-28 00:47 UTC
**Describe the bug**
Select2 seems to not be applied/working on the appropriate field types out of the box. Bug is observed on the Job tags field with type `term-multiselect` (also true for `multiselect`). Same thing is true for Job category, so I think it's just a general problem with multiselect and Select2 not being actually used and/or conflicting with Ultimate Member and their Select2, although Select2 works just fine on UM forms.

**To Reproduce**
1. Go to Job submission page (called via shortcode; no other content in the page)
~~2. Click on '....'~~
3. Scroll down to 'Job tags' section
4. See the multiselect functionality

**Screenshots**
Screenshot on how it appears without any changes (field type is 'term-multiselect'):
![image](https://user-images.githubusercontent.com/13751597/187052363-f81eb542-5168-4d22-a782-93a539916525.png)

Screenshots on how it appears after applying `jQuery('select').select2()` through the console:
![image](https://user-images.githubusercontent.com/13751597/187052391-03faf22e-0dd7-4d77-9abf-3255f8a98151.png)
![image](https://user-images.githubusercontent.com/13751597/187052398-4e6466fb-6bc1-43c9-82fc-5810d242f249.png)

**Expected behavior**
To display a multiselect Select2 dropdown, like on the second set of screenshots. (The Select2 dropdown needs to be set with margin-top to be put into the right place, but I didn't do it in the screenshots)

**Isolating the problem (mark completed items with an [x]):**
~~- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.~~
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.0.1
- WP Job Manager Version: 1.37.0 
- PHP Version: 7.4.30
- Other important details:
    - Ultimate Member version: 2.5.0

**Comment by tripflex** [comment] 2022-09-06 20:58
Duplicate of https://github.com/Automattic/WP-Job-Manager/issues/2002

**Closed as completed by tripflex** 2022-09-06 20:58 UTC
Labels: Bug
