### ISSUE TITLE
class WP_Job_Manager_Writepanels miss 'required' option building text inputs

### ISSUE THREAD

**Issue by jonnyjava** [Automattic/WP-Job-Manager#681] opened 2016-05-19 15:28 UTC
#### What I Expected To Happen

I expected this 
`<input type="text" required="" value="" placeholder="" id="_exequatur" class="" name="_exequatur">`
#### What Happened Instead

I got this one 
`<input type="text" value="" id="_exequatur" class="" name="_exequatur">`
Required option is missing

#### Steps to Reproduce the Bug

Create a custom field for the admin in this way
```
function admin_exequatur_field( $fields ) {
  $fields['_exequatur'] = array(
    'label'       => 'label does not matter,
    'type'        => 'text',
    'required'    => true,
    'description' => ''
  );
  return $fields;
}
```
As explained [here](https://wpjobmanager.com/document/tutorial-adding-a-salary-field-for-jobs/)

#### Proposed solution
add this
`<?php if ( ! empty( $field['required'] ) ) echo 'required'; ?>`
at the end of [this line](https://github.com/Automattic/WP-Job-Manager/blob/master/includes/admin/class-wp-job-manager-writepanels.php#L192)
Just before the input closing tag `/>`

**Comment by tripflex** [comment] 2016-06-02 03:10
That is correct and is by design, the admin section does not support required arguments.

Adding the code to output `required='required'` when that argument is set wouldn't be hard to do, but that also is **only for HTML5** and does not support any other field types, or browsers that do not support HTML5.

What you are suggesting would not actually make that field "required" and could be confusing to some people.

I'm not sure if this should (or would) be a feature added as you can very easily override the method/function called for admin inputs by using the `job_manager_input_FIELDTYPE` action and then outputting whatever you want.  

For your situation it would specifically be
`job_manager_input_text`

Just add that as an action, and then call your own function to output just like the core one does, but with your own changes.

IMO this should only be added if we plan on fully supporting required fields in admin section, which I do not think will happen.

**Comment by chaselivingston** [comment] 2016-08-05 19:57
@jonnyjava @tripflex Is this still an issue or can we close?

**Comment by tripflex** [comment] 2016-08-09 01:53
@chaselivingston i would say close it ... mainly because if an admin wants to empty out a required field, this would prevent them from saving in the admin section ... just a thought

**Comment by jonnyjava** [comment] 2016-08-09 06:03
I tried your suggestion and it worked. SO for me the problem has been solved and the issue can be closed

**Closed** 2016-08-09 11:31 UTC
