### ISSUE TITLE
Job visibility issue

### ISSUE THREAD

**Issue by Gnodesign** [Automattic/WP-Job-Manager#2371] opened 2023-03-10 10:58 UTC
**Describe the bug**
I got a report from one of my clients that the visibility options don't work when you set them to **All Users** or **Anonymous**. I have tested this and I can confirm that all other roles work fine except for these 2 options.

**To Reproduce**
1. Go to "Job Listings -> Settings -> Job Visibility"
2. Set **View Job Capability** to **All Users** or **Anonymous**
3. Visit a single job listing as logged in if the setting has been set to **All Users** or as not logged in if the setting has been set to **Annonymous**
4. You will see the message "Sorry, you do not have permission to browse job listings.".

**Expected behavior**

- When **All Users** has been set in the settings all logged in users should be able to view the page.
- When **Anonymous** has been set in the settings all non logged in users should be able to view the page.

**Comment by Gnodesign** [comment] 2023-03-10 11:02
Did some further testing and it seems the same issue also happens with Resume Manager plugin.

**Comment by mikeyarce** [comment] 2023-03-22 18:52
Hi @Gnodesign - thanks for the report!

When you say `Set View Job Capability to All Users or Anonymous` - can you explain more about what you mean?  I don't see `Anonymous` as an option with just the default plugin enabled - maybe there's a third-party plugin adding that?  For "All Users" - do you mean just adding ALL the capabilities to the list, or do you mean leaving it blank so that "Everyone (Public)" can see it?

**Comment by gikaragia** [comment] 2023-06-01 13:45
Resolving as there are no 'All Users' or 'Anonymous' options by default. Let us know @Gnodesign if you have more information on how to reproduce this.

**Closed as completed by gikaragia** 2023-06-01 13:45 UTC
Labels: [Status] Needs Author Reply, Bug

**Comment by gikaragia** [comment] 2023-06-02 08:05
Probably a duplicate of https://github.com/Automattic/WP-Job-Manager/issues/2371
