### ISSUE TITLE
Stats for jobs 

### ISSUE THREAD

**Issue by joblux** [Automattic/WP-Job-Manager#1933] opened 2019-11-07 20:30 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I dont see stats for views of jobs or stats for resumes, is it something you are working on ?

**Comment by jom** [comment] 2019-11-07 21:28
Duplicate of #1733

**Closed by jom** 2019-11-07 21:28 UTC
