### ISSUE TITLE
user-submitted hyperlinks randomly broken

### ISSUE THREAD

**Issue by pguilha** [Automattic/WP-Job-Manager#2029] opened 2020-06-16 12:10 UTC
Hi,

Sorry that this is not going to be the best detailed bug report, because I'm at a loss as to how to reproduce it.
On a few jobs posted by users (found 8 jobs with the problem in 200+ so far), it seems the links they've included in their listing are broken in a very odd way. For example, `http://usuaris.idibell.cat/en` became `””//idibell.cat/en/”””`
I don't know how this can be user error or how to reproduce it. Could it be something to do with which browser people are using? 

I'm at a loss and would appreciate some guidance!
thanks

**Comment by Hastibe** [comment] 2020-08-18 05:57
I would recommend also posting in the WordPress.org [support forum for WP Job Manager](https://wordpress.org/support/plugin/wp-job-manager/).

**Comment by alexsanford** [comment] 2020-08-19 16:58
Yes, the support forum would be a better avenue for this issue, since we don't have clear steps to reproduce it.

Alternatively, if you have purchased any first-party extensions for WPJM, you can log into your wpjobmanager.com account and directly contact support from there, and they will help you debug and work through the problem.

As a first step, I would try to understand if there are any commonalities between the times when it happened. Is it all the same user? Does it happen when that user tries to post another listing with the same link? Are they using the same browser?

If you can find a consistent way to make it happen, then my next suggestion would be to try to narrow down whether it is a plugin or theme compatibility issue. Try switching to a default theme and deactivating other plugins, to see if one of them causes the problem to go away.

I'm going to close this, since this repo is reserved for reproducible bugs and enhancement requests, but feel free to continue the conversation on the forums or directly with our support, as per the above suggestions 🙂

**Closed by alexsanford** 2020-08-19 16:58 UTC
Labels: [Type] Bug
