### ISSUE TITLE
show pagination problem

### ISSUE THREAD

**Issue by aga2442** [Automattic/WP-Job-Manager#2019] opened 2020-05-29 16:20 UTC
I need your support on a subject.

For example: visitor examines xxxx job listings page.

There are 150 listings on that page.

an listing attracts the visitor’s attention.

After reviewing the ad, the browser returns to the page where it is left with “fall back”.

but at this stage, the whole page is at the top.

When the visitor comes to the 100th listing, he loses where he is.

because of this i get a lot of complaints.

and

I’m losing visitors.

how can I prevent this?

standard display site:

https://workscout.in/jobs/

the structure that should be:

https://demo4.madrasthemes.com/jobhunt/jobs/

Listing systems all over the world are composed of new page urls.

for this wpjm, it's a big deficiency.

**Comment by alexsanford** [comment] 2020-05-29 19:30
> but at this stage, the whole page is at the top.

What version of WP Job Manager are you using? This issue was fixed in a recent version, and may be fixed by upgrading.

Closing this issue since it is not a reproducible bug. If you are still seeing this on the latest version of WP Job Manager, then please either ask a question in the [forum](https://wordpress.org/support/plugin/wp-job-manager/), or if you have purchased a WP Job Manager extension then feel free to reach out to our [support team](https://wpjobmanager.com/support/).

**Closed by alexsanford** 2020-05-29 19:30 UTC

**Comment by aga2442** [comment] 2020-05-29 21:35
@alexsanford 

the latest version is active.

no. In the last version, such a feature did not come.

I also posted several times on this topic in wordpress forums.

please check: https://wordpress.org/support/topic/lose-page-rank/
