### ISSUE TITLE
Job Dashboard links (delete/duplicate) don't work

### ISSUE THREAD

**Issue by Hopfenbraeu** [Automattic/WP-Job-Manager#968] opened 2017-05-16 11:34 UTC
#### What I Expected To Happen

In the job dashboard, after clicking "duplicate" the job should be duplicated. After clicking "delete" the job should be deleted.

#### What Happened Instead

After clicking "duplicate" or "delete" the page refreshes without any actions - the Job is not duplicated or deleted. 

#### Steps to Reproduce the Bug

It worked fine for several months and suddenly stopped working. I did no updates or change anything, so im totally baffled why it is not working anymore.
https://guides.github.com/features/mastering-markdown/
Only the "edit" button works in the job dashboard for any user / user group.

**Comment by jom** [comment] 2017-05-16 14:57
I'm unable to reproduce with **Twenty Sixteen**. Have you set your pages under Job Listings > Settings > Pages? If so, what is your theme?

**Comment by spencerfinnell** [comment] 2017-06-15 14:33
Closing as can't reproduce and lack of author feedback.

**Closed by spencerfinnell** 2017-06-15 14:33 UTC
Labels: [Status] Needs Author Reply, [Type] Bug
