### ISSUE TITLE
Categories not showing on job page

### ISSUE THREAD

**Issue by pandanas69** [Automattic/WP-Job-Manager#2190] opened 2021-10-20 04:54 UTC
Hi,
I have enabled categories and added a bunch but not showing in drop-down. Only one shows.
Using wp job manager and core plugins. Bootscore, bootsrap 5 theme. Latest WordPress, php 7?

Thanks

**Comment by aaronfc** [comment] 2022-02-15 17:32
Hi @pandanas69,
First of all I am sorry for the delay. I was going through old bug reports and saw yours.

Unfortunately I can not reproduce your issue.

Could you confirm you are still experiencing this?
If positive, we would need some further details on how to reproduce it.
An screenshot would be awesome too.

Thanks for your help.

**Comment by mikeyarce** [comment] 2023-03-02 21:48
Closing this as we don't have further information and cannot reproduce.

**Closed by mikeyarce** 2023-03-02 21:48 UTC
Labels: [Type] Bug, [Status] Needs Author Reply
