### ISSUE TITLE
Search in Jobs Dashboard

### ISSUE THREAD

**Issue by workpei25** [Automattic/WP-Job-Manager#2617] opened 2023-10-13 18:10 UTC
### Is your feature request related to a problem? Please describe
WPJM Applications add-on provides employers with a Jobs Dashboard that amounts to a table with the relevant details and, if present, a link to any applications received for each job.

For employers with a large number of jobs theres is no way to search the Dashboard. So they must scroll through pages of listings. Many become frustrated and give up, opting instead to just create a new listing.

### Describe the solution you'd like
Ideally the jobs dashboard could be equipped with either a dropdown with their current jobs to select from, or worst case scenario a simple keyword field to search for an existing job.

**Comment by Scotm19** [comment] 2023-10-13 18:22
WPJM Applications add-on provides employers with a Jobs Dashboard that amounts to a table with the relevant details and, if present, a link to any applications received for each job.

For employers with a large number of jobs theres is no way to search the Dashboard. So they must scroll through pages of listings. Many become frustrated and give up, opting instead to just create a new listing.

Ideally the jobs dashboard could be equipped with either a dropdown with their current jobs to select from, or worst case scenario a simple keyword field to search for an existing job.

**Comment by gikaragia** [comment] 2023-11-13 15:17
Thank you for the suggestion @Scotm19. We will add this to our queue of future projects for consideration.

**Comment by gikaragia** [comment] 2023-11-13 15:18
Possible duplicate of https://github.com/Automattic/WP-Job-Manager/issues/2617

**Comment by Gnodesign** [comment] 2023-11-14 23:24
Duplicated request: https://github.com/Automattic/WP-Job-Manager/issues/667

+1 for this feature! 
Throughout the years, a lot of Cariera customers have been asking for this functionality as well.

**Comment by thedebian** [comment] 2023-11-20 13:38
Closing as duplicate of #667

**Closed as completed by thedebian** 2023-11-20 13:38 UTC
Labels: Enhancement
