### ISSUE TITLE
Snippet interferes with sending email after job submission

### ISSUE THREAD

**Issue by verysiberian** [Automattic/WP-Job-Manager#1577] opened 2018-08-19 19:41 UTC
Hello! You all have posted this helpful snippet on the WP Job Manager website:

https://wpjobmanager.com/customization-snippets/#redirectToJD

After a job is submitted, it redirects the user to the job dashboard page. However, at least in my case, it disrupts the email notification sent to the admin (if configured) after a new job is submitted. Providing an updated snippet would be greatly appreciated if possible. Thank you.

**Comment by iamgabrielma** [comment] 2018-09-03 09:46
Hello there!

Could you clarify what you mean by "disrupts the email notification sent to the admin (if configured) after a new job is submitted" ? 

Please be sure to share reproducible steps to so we can take a better look into it, as well as deactivate all plugins except WP Job Manager, switching themes to a default WordPress theme like Twenty Sixteen, and testing again to check if is a plugin/theme conflict :)

**Comment by verysiberian** [comment] 2018-09-03 22:26
Thanks for your reply. What I mean is that the email notification does NOT get sent to the admin even when that option is configured in the settings.

**Comment by iamgabrielma** [comment] 2018-09-05 14:52
Thanks for clarifying! After some testing I've been able to reproduce this, as far as I see this seems to be due the job not going through the whole flow process, and it remains set as `preview` : 

<img width="1147" alt="screen shot 2018-09-05 at 21 44 16" src="https://user-images.githubusercontent.com/3812076/45101140-08a27080-b155-11e8-827a-597f6496b7fe.png">

With exactly the same setup but without the snippet running, the job flow is completed and the notifications are triggered:

<img width="931" alt="screen shot 2018-09-05 at 21 47 40" src="https://user-images.githubusercontent.com/3812076/45101323-6767ea00-b155-11e8-8f24-ee2c0a53b7c0.png">

Could you check if the same happens on your end?

This is possibly due to filtering `done()` on https://github.com/Automattic/WP-Job-Manager/blob/ca393939543a49046494a705c7edcf65e7ba8480/includes/forms/class-wp-job-manager-form-submit-job.php#L878

**Comment by verysiberian** [comment] 2018-09-05 14:57
Thanks and yes, I get the same result. The notifications are sent to the admin when the snippet is NOT active (commented out or deleted). Unfortunately, if the snippet is active, notifications to admin are disabled. It would be wonderful if either the plugin or snippet could be updated so they could peacefully co-exist. :)

Best,
Rob

**Comment by iamgabrielma** [comment] 2018-09-05 15:08
Great Rob, thanks for confirming.

For the moment, if you'd like to keep the snippet I'd recommend to go to your job submissions under Job Listings > All Jobs and then in the Preview tab > Actions > Edit > Publish . So your jobs will appear on the site.

This will not trigger the notifications either, but at least the jobs will be visible.

Regarding the bug that the snippet introduces I'll let the developers jump in and share their thoughts, as is not a core bug that needs to be fixed but something introduced by a snippet we offer on the developer documentation to change the plugin default behavior.

**Comment by iamgabrielma** [comment] 2018-09-06 07:49
Hi Rob,

After checking with the developers they'll test and update the snippet to make it work properly, I'll close this issue for the moment in favor of the open one in our private repository. I'll update this issue with a comment when this is fixed.

Best,

**Closed by iamgabrielma** 2018-09-06 07:49 UTC
Labels: [Type] Question

**Comment by verysiberian** [comment] 2018-12-18 16:44
Hello! I'm just wondering if the snippet or plugin were ever fixed to address this bug. Thanks.

**Comment by iamgabrielma** [comment] 2018-12-20 12:08
Hi @verysiberian ,

Not at the moment. This issue was affecting other functionalities within the plugin as is still being worked on. We have a [PR](https://github.com/Automattic/WP-Job-Manager/pull/1624) in place for the upcoming 1.3.2 version that will possibly fix this, please let us know if you keep experiencing problems after that update.

**Comment by aheckler** [comment] 2019-02-15 10:20
Good news! This has been released. :) The snippet is now:

```
add_filter( 'job_manager_job_submitted', function() {
    if ( wp_redirect( job_manager_get_permalink( 'job_dashboard' ) ) ) {
	  exit;
	}
}, 20 );
```

**Comment by verysiberian** [comment] 2019-02-15 21:03
Thank you very much for fixing it!
