### ISSUE TITLE
Email application method does not accept + in email address

### ISSUE THREAD

**Issue by edd677** [Automattic/WP-Job-Manager#864] opened 2017-02-01 16:28 UTC
#### What I Expected To Happen

Employer posted job using "careers+java@companyx.com". Expected the back-end field to indicate this, as usual.

#### What Happened Instead

After publishing the job, the back-end field changes to ""careers java@companyx.com" (note the lack of the + sign, and instead a space).

#### Steps to Reproduce the Bug

Post a job using an email address containing a "+". Publish as the admin and view the listing on the back-end.

**Comment by tripflex** [comment] 2017-02-16 05:28
Thanks for reporting this, looks like only in admin area `urldecode` is being ran on the value before being updated (this replaces + with spaces), added a PR to fix this

**Comment by edd677** [comment] 2017-02-17 09:46
@tripflex - I'm not sure if you were suggesting this was the case, but it appears this issue is not isolated to updated a listing in the admin area. It also occurs when an employer posts a job on the front-end. When the job is first viewed on the back-end (i.e. as a pending listing), the space is already there. Thanks!

**Comment by tripflex** [comment] 2017-02-23 01:56
@edd677 yes this is the fix for that issue, and i'm not sure what leads you to believe that, but I tested this using a blank install and confirmed when updating a listing (and creating a blank one) from the frontend, the `+` remains without issues.

**Comment by kraftbj** [comment] 2017-03-08 15:41
Closed in #871

**Closed by kraftbj** 2017-03-08 15:41 UTC
Labels: [Pri] Normal, [Type] Bug
