### ISSUE TITLE
Employer Notice of Expiring Job Listings does not work

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/WP-Job-Manager#2091] opened 2020-12-18 07:50 UTC
**Describe the bug**
The email notification for _Employer Notice of Expiring Job Listings_ does not work. No emails are triggered.

**To Reproduce**
1. Enable _Employer Notice of Expiring Job Listings_ in Job Listings > Settings > Email Notifications
2. Create a job listing that expires soon
3. Wait for the expiry email matching the expiry period in the email notifications

No emails are triggered.

**Expected behavior**
Email is triggered.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.6
- WP Job Manager Version: 1.34.5
- PHP Version: 7.3.25

First reported in 3567943-zen

**Comment by tripflex** [comment] 2021-01-07 21:54
Also reported here https://wordpress.org/support/topic/employer-notice-of-expiring-job-listings/

**Comment by dericleeyy** [comment] 2021-01-12 08:32
The email notification might not work for employers as well.

3621896-zen

**Comment by jom** [comment] 2021-01-14 12:36
I'm not able to reproduce when I just tested this, but a couple of notes just to make sure these were considered:
- The notice period should catch jobs in `x` days, not _within_ `x` days. So if it is set to 10 days and it is 2020-01-01, it should look for jobs expiring on `2020-01-10`. 
- This is not calculated very precisely so it is a bit difficult to predict _when_ a notice will be sent. The reason for this is because we're [incorrectly] using a mix of GMT and PHP timezone (but never WordPress timezone). That said, in theory it should still send notices (just maybe +/- 1 day from the day you think it should). We should probably create a separate issue to fix the timezone issues in our implementation.

**Comment by donnapep** [comment] 2021-06-04 12:14
@dericleeyy I wasn't able to reproduce this either, so I'm going to close it. If it's determined that the issue actually has to do with what Jake described at https://github.com/Automattic/WP-Job-Manager/issues/2091#issuecomment-760169306, then we could open a separate issue.

**Closed by donnapep** 2021-06-04 12:14 UTC
Labels: [Pri] Normal, [Status] Queued, [Type] Bug
