### ISSUE TITLE
Job drafts empty after saving

### ISSUE THREAD

**Issue by Braehler** [Automattic/WP-Job-Manager#1860] opened 2019-08-14 05:48 UTC
#### Steps to Reproduce
1. Customer had an active listing or is creating a listing
2. Saves the draft, success message is shown
3. Continue to edit the draft later, and the draft is empty except the title

#### What I Expected
When continuing to edit the draft, all previously filled fiels should show up, including the images

#### What Happened Instead
Drafts are empty except the title and the company logo.
But in the admin area you can see content of the listing
This can be caused by 2 things:
Either there is problem with the "draft status" on its own. Because when you manualy change the status in the admin area from "draft" to "outdated" the user gets the prefilled data back
or
There is a conflict with the WC PAid Listings add on. If you choose a different duration of the listing when you continue to edit the listing, all prefilled fields are gone. When you choose the same duration the listing is prefilled.

#### WordPress / WP Job Manager Version
Word Press 5.2.2
WPJM: 1.33.3

#### Browser / OS Version
FF 68-0.1 64bit
Chrome: 76.0.3809.100 64bit

**Comment by richardmtl** [comment] 2019-08-19 15:12
Hi!

I am unable to reproduce this; however, we do have an open issue where something similar happens, with the WC Paid Listings addon. I will close this issue in favour of that one, then. Since that issue is in a private repository, you won't be able to see it, but *we* will be able to see the link between the two, and get back to you when we resolve it. 

Also, this issue is very familiar to me; do you have a forum thread open for it? If so, can you link to it, please? Thanks!

**Closed by richardmtl** 2019-08-19 15:12 UTC

**Comment by Braehler** [comment] 2019-08-20 06:28
Hey,
here is the link to the open thread in the forum:
https://wordpress.org/support/topic/job-drafts-empty/
