### ISSUE TITLE
display a list of jobs

### ISSUE THREAD

**Issue by Mary19Star** [Automattic/WP-Job-Manager#2137] opened 2021-04-03 19:55 UTC
hello i’m using this plugin and i start changing the content-job-listing.php by adding the discription field
but when i click on show more i can see just the first post discription and not the others i think i should add the post id but i dont know how. this is the code if someone can help
TIA

```
<?php
/**
 * Job listing in the loop.
 *
 * This template can be overridden by copying it to yourtheme/job_manager/content-job_listing.php.
 *
 * @see         https://wpjobmanager.com/document/template-overrides/
 * @author      Automattic
 * @package     wp-job-manager
 * @category    Template
 * @since       1.0.0
 * @version     1.34.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

global $post;
?>

<li style=" border: 1px solid black; padding: 20px; margin-bottom: 30px;" <?php job_listing_class(); ?> data-longitude="<?php echo esc_attr( $post->geolocation_long ); ?>" data-latitude="<?php echo esc_attr( $post->geolocation_lat ); ?>">
<!-- 	<a href="<?php the_job_permalink(); ?>">
 -->		<!-- <?php the_company_logo(); ?> -->
		<div  class="work-section" >
			<h3><?php wpjm_the_job_title(); ?></h3>
			<!-- <div class="company">
				<?php the_company_name( '<strong>', '</strong> ' ); ?>
				<?php the_company_tagline( '<span class="tagline">', '</span>' ); ?>
			</div> -->
		</div>
		<!-- <div class="location">
			<?php the_job_location( false ); ?>
		</div> -->

		<div   id="collapseExample" class=" collapse job_description">
			<?php wpjm_the_job_description(); ?>
		</div>

		<center>
		<div class="vc_btn3-container  red-btn vc_btn3-inline"  style="margin-top: 20px">
			 <a style="text-align: center;" href="<?php the_job_permalink(); ?>">
			 Imprimer l’offre 
			</a>
		</div>

		<div class="vc_btn3-container  black-btn vc_btn3-inline"  style="margin-top: 20px">
			 <a style="text-align: center;" href="<?php the_job_permalink(); ?>">
			 Postuler 
			</a>
		</div>

		<div class="vc_btn3-container  red-btn vc_btn3-inline"  style="margin-top: 20px">
			 <a  href="#what" data-toggle="collapse" aria-expanded="false" data-target="#collapseExample"  aria-controls="collapseExample" style="text-align: center;" >
				 <span class="collapsed"> En lire plus </span>
      			 <span class="expanded"> En lire moins </span>
			</a>
		</div>
		
		 </center>
		<ul class="meta">
			<?php do_action( 'job_listing_meta_start' ); ?>

			<?php if ( get_option( 'job_manager_enable_types' ) ) { ?>
				<?php $types = wpjm_get_the_job_types(); ?>
				<?php if ( ! empty( $types ) ) : foreach ( $types as $type ) : ?>
					<li class="job-type <?php echo esc_attr( sanitize_title( $type->slug ) ); ?>"><?php echo esc_html( $type->name ); ?></li>
				<?php endforeach; endif; ?>
			<?php } ?>

<!-- 			<li class="date"><?php the_job_publish_date(); ?></li>
 -->
			<?php do_action( 'job_listing_meta_end' ); ?>
		</ul>
	<!-- </a> -->
</li>
```
ps: show more is the : <span class=”collapsed”> En lire plus </span>

**Comment by alexsanford** [comment] 2021-08-20 18:02
Closing this as it is not a bug in WP Job Manager, and assisting with customizations is outside the scope of our support. This sounds like it should be possible, though, and something a developer should be able to help out with 🙂

**Closed by alexsanford** 2021-08-20 18:02 UTC
Labels: [Type] Bug
