### ISSUE TITLE
Employers can't post job

### ISSUE THREAD

**Issue by greggdana** [Automattic/WP-Job-Manager#2042] opened 2020-07-29 13:55 UTC
Getting numerous employers experiencing this same issue. 1). They enter account dashboard, hit post a job button, and it redirects back to account dashboard. They cannot post
 
"I have registered for your site and I am trying to create a job posting but it keeps going back to the same dashboard landing page. I have tried clearly my browser cache a few times but it hasn't helped."

**Comment by alexsanford** [comment] 2020-08-17 19:11
Hi there! I just tried this on the latest version of WP and WPJM with a default theme and it works on my end. I would suggest the following:

- For debugging purposes, try it with a default theme, and consider deactivating other plugins to see if any of them are interfering.
- If you have purchased any official WPJM add-on package, log into your account on wpjobmanager.com and contact support from there. They will help you get to the bottom of the issue on your site.
- If you have not made a purchase from us, please post to the [WP Job Manager forum](https://wordpress.org/support/plugin/wp-job-manager/) for help.

Closing this issue, since this repo is reserved for reproducible bugs and feature requests.

**Closed by alexsanford** 2020-08-17 19:11 UTC
Labels: Bug
