### ISSUE TITLE
"Create A New Job" button does not actually create a job

### ISSUE THREAD

**Issue by portnovyury** [Automattic/WP-Job-Manager#2047] opened 2020-08-09 07:57 UTC
**Describe the bug**
The issue appears when you create a job posting without publishing immideately. When you try to add a new job posting having previous job drafted, the form for a new job will unevidably reset when you intend to go to preview. 

**To Reproduce**
1. Go to "Post a job" page, where [submit_job_form] shortcode is
2. Fill out the form and click on "Preview" button
3. Do not publish this particular job - instead, navigate to "Post a job" page again. 
4. You will see a message "You are editing an existing job. Create A New Job?"
5. Once "Create A New Job" link is clicked, a job submission form will be opened, and the following arguments will be added to the URL ?new=1&key=5f2f9fc39346a (for example) - which indicates that you are about to create a new job, instead of editing the previously created draft.
6. Full out the form and click "Preview" button
7. No job posting will be created, also no errors will be shown. The page will just reload, losing all the data from the form inputs. There will be no GET arguments either.

**Expected behavior**
Once you click the "Preview" button of the last filled form, the job posting Draft should be created, and the visitor should be taken to "Job Preview" page. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.4.2
- WP Job Manager Version: 1.34.2
- PHP Version: 7.2
- Other important details: No other plugins, Twenty Twenty theme

**Comment by jom** [comment] 2020-08-10 15:42
I believe this is a duplicate of #2028. Fix has been merged and should be released today or tomorrow.

**Closed by jom** 2020-08-10 15:42 UTC
Labels: [Type] Bug
