### ISSUE TITLE
Unable to submit jobs after recent update due to UX design

### ISSUE THREAD

**Issue by dianaascher** [Automattic/WP-Job-Manager#2023] opened 2020-06-02 17:03 UTC
**Describe the bug**
Ever since the most recent update, we’re unable to receive new job submissions, because the entry fields overlap, regardless of page layout selection. Please see https://www.islab.gseis.ucla.edu/wp-content/uploads/2020/06/post-a-job-ux-design-flaws.png for an image. I’ve received several emails from people who want to post, yet are unable to enter content into the hidden fields.

**To Reproduce**
1. Go to https://www.islab.gseis.ucla.edu/contact/post-a-job/
2. Try to enter details in each field
3. See problem

**Screenshots**
Screenshot here: https://www.islab.gseis.ucla.edu/wp-content/uploads/2020/06/post-a-job-ux-design-flaws.png

**Expected behavior**
I’d expect the layout of the form to adapt to the theme page templates so people may submit job ads.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.4.1
- WP Job Manager Version: 1.34.2
- PHP Version: 7.0
- Other important details:

**Comment by alexsanford** [comment] 2020-06-11 16:19
Thank you for the detailed report.

You've indicated above that you tested this with all other plugins deactivated, and using a default WordPress theme. I do not see the same problem when I test using the latest version of the default TwentyTwenty theme. Which theme did you test on? Were there any plugins that you may have missed when deactivating all of them? Can you send a screenshot of this happening on a default theme with other plugins deactivated?

This seems like it is probably an issue with either a plugin or the theme on your site. If you have an active license for any WP Job Manager extension, I would suggest contacting support directly on wpjobmanager.com and they will help you get to the bottom of this. If you do not have a license, it would be best to post in the [plugin support forum](https://wordpress.org/support/plugin/wp-job-manager/), which our support folks also monitor.

**Comment by tripflex** [comment] 2020-06-11 16:24
This is due to your theme setting CSS on `.field` class which is causing this:
https://www.islab.gseis.ucla.edu/wp-content/themes/center-digital-humanities-_sol-theme-164d2444c94e/library/css/style.css

Specifically setting `width` and `height` on anything with a class `field`

**Comment by alexsanford** [comment] 2020-06-11 16:31
Thanks @tripflex. I can confirm that disabling the `width` and `height` rules in the browser tools for the theme CSS solves the problem.

Closing this issue as it is not a bug in WP Job Manager, but please do feel free to contact support or open a forum thread (as described above) for further help with this.

**Closed by alexsanford** 2020-06-11 16:31 UTC
Labels: [Status] Needs Author Reply, [Type] Bug

**Comment by dianaascher** [comment] 2020-07-30 05:17
Thank you, @alexsanford @tripflex @stephdau @folletto ! I will do as you’ve suggested. I really appreciate the thorough guidance.
