### ISSUE TITLE
Job Alerts categories interfering with Search filter Categories 

### ISSUE THREAD

**Issue by dauand** [Automattic/WP-Job-Manager#967] opened 2017-05-15 10:11 UTC
When a user creates a job alert by selecting some job categories (in multiple categories disabled mode), then the search filter shows only those categories as possible dropdown options.

**Comment by jom** [comment] 2017-05-15 17:03
I'm not able to reproduce. Are you sure you have job listings assigned to those categories?

**Comment by dauand** [comment] 2017-05-16 08:17
Hi,

I don’t know where did you try. If on our website, then now it is set to allow multiple categories, so every single one appears as normal. However, if I set it to single category (dropdown, instead of multiselect), it is then affected.

Kind regards,
Andrius

**Comment by jom** [comment] 2017-05-16 10:51
Would you mind providing screenshots and links?

**Comment by dauand** [comment] 2017-05-16 11:09
Alright, I think I misinterpreted the events – apologies for that. In a single category selection mode, should it show all available categories or only the ones with active (published) jobs? Because now it seems to be the case and it simply coincided with the categories selected in the alert. But that still raises the question, why such difference?

Kind regards,
Andrius

**Comment by jom** [comment] 2017-05-16 11:21
It is common in WordPress-land to only return terms that have published posts associated with them. The `hide_empty` argument of [get_terms()](https://developer.wordpress.org/reference/functions/get_terms/) is `true` by default and we also set it as true in `job_manager_dropdown_categories()`.

**Closed by jom** 2017-05-16 11:21 UTC
Labels: [Status] Needs Author Reply, [Type] Plugin Issue
