### ISSUE TITLE
Change previewing behavior

### ISSUE THREAD

**Issue by annezazuu** [Automattic/WP-Job-Manager#727] opened 2016-07-25 19:39 UTC
A user in 2681379-t has suggested a change in the way the preview works for job listings offering both of these ideas as possible enhancements:

> 1. When and Employer clicks on PREVIEW to preview their job listing 
>    creation, a warning appears asking them if they are sure they want to 
>    Preview the job and tells them that if the close the Preview window 
>    instead of using the EDIT LISTING button they will lose their work. If 
>    they click "I Understand, lets Preview" they get the preview. If they 
>    click "Not Yet" (or some button that communicates future possibility) 
>    then they simply don't enter the Preview mode yet.
> 2. If they click "I Understand, let's Preview" (or something similar) 
>    the Preview appears. If they attempt to leave that screen incorrectly, 
>    is it possible that it could behave like WordPress does when you are 
>    editing a page and then try to close the window without saving, so that 
>    it asks if you are sure before letting you do it? If they say YES, the 
>    entire job listing is deleted. If they say NO it keeps them at the 
>    preview window until they select a valid option.

I'm not sure which would be easier to implement or why the previewing behavior is set up the way it is currently but posting here as an enhancement :)

**Comment by tripflex** [comment] 2016-08-09 01:32
IMO there is nothing wrong with the way the preview step works, and it's pretty clear that you have to SUBMIT the listing while on the preview page, I don't see what the problem is?

1. Fill out the form
2. Click Preview to preview how the listing would look
3. If you like how it looks, click Submit, if not, click Edit or use back button

If the user doesn't like that process, it's as easy as removing the preview step with tutorial already on wpjobmanager.com:
https://wpjobmanager.com/document/remove-the-preview-step/

Sounds to me like this user just wants it a specific way for their site, in which that would be customization they should handle on their own.  

If their users are filling out the form, clicking preview, and then closing the browser window or clicking on another link, they probably need to look at their theme.

If something was to be implemented, the only thing I can think that would be worth wild would be a message box when the user attempts to leave the page, but even then, it would need to prevent that message box from showing if the user clicks submit, edit, or the back button, as all those are legitimate flows.

**Comment by bikedorkjon** [comment] 2017-05-05 00:44
User in 3195832-t was asking since we save the preview step as a preview post_status if we could reinstate that listing when they go back to add a listing.

**Comment by davoraltman** [comment] 2017-05-08 18:07
3202104-t

Feedback from a user regarding the Preview step:

> I was wondering if I could recommend a new feature whereby the job/listing form is actually in the preview view, i.e. rather than clicking on preview to view the listing before submitting, you could streamline the process to have the user upload information to a listing in the preview form as it would look when live. This would stop a user going back and forth to get the right 'look' for their listing between the form and the preview page which is a bit tedious and leading to user fatigue in some cases. 

This would be a really nice improvement! It requires a lot of work, though, but it would be nice to have it eventually :)

**Comment by rachelsquirrel** [comment] 2017-05-09 06:57
Just following up on issue 3195832-t. The user would like to be able to save the listing in Preview mode but not submit it. It would be saved as a draft for editing later.

**Closed** 2018-03-26 18:45 UTC
Labels: [Type] Enhancement
