### ISSUE TITLE
Unintended Date Field Change Upon Posted Position Edit

### ISSUE THREAD

**Issue by cbmitchell1** [Automattic/WP-Job-Manager#836] opened 2016-12-14 23:06 UTC
I opened one of my previously posted listings to make a quick content change, and uploaded it no problem. It was only later that I recognized the bug where each time I edit a posted listing, the closing date and listing expiration fields change to one day earlier than intended (i.e. December 15th-->December 14th). This bug occurs every time I open a posted listing to edit, regardless of whether I choose to re-upload.

Steps to replicate:

1.  Click on a posted Position Name, noting the current closing date field entry
2. Notice the date-field change to one day earlier.

**Comment by kraftbj** [comment] 2016-12-16 04:45
Duplicate of #822

**Closed by kraftbj** 2016-12-16 04:45 UTC
Labels: duplicate
