### ISSUE TITLE
When posting a job, only 1 user can preview and submit the job. When every other user clicks "preview" nothing happens

### ISSUE THREAD

**Issue by helenswitch** [Automattic/WP-Job-Manager#2199] opened 2021-11-30 07:50 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

**Comment by alexsanford** [comment] 2021-11-30 17:07
Hi there! Could you please fill in the description of this bug report with the information requested by the template? Also include clear steps to reproduce the issue.

**Comment by helenswitch** [comment] 2021-12-08 10:37
1. Click on the "Post a job" page
2. Type in all the details
3. Click "preview"
4. Nothing happens for all users, except 1 user

![Capture](https://user-images.githubusercontent.com/95274729/145193697-7d24daf8-8b66-4699-81aa-a7c2934849ce.JPG)

**Comment by alexsanford** [comment] 2021-12-08 17:31
Thanks for the additional info! This looks like it might be an issue specific to your site, as we haven't seen this as a general problem within WPJM. I would suggest posting this to the [support forums](https://wordpress.org/support/plugin/wp-job-manager/) and someone will reach out there with some next steps for debugging.

Closing this for now as it isn't a reproducible bug, but feel free to reopen with new info if needed! 🙂

**Closed by alexsanford** 2021-12-08 17:31 UTC
Labels: [Type] Bug, [Status] Needs Author Reply
