### ISSUE TITLE
Create Job Report Summaries

### ISSUE THREAD

**Issue by annezazu** [Automattic/WP-Job-Manager#1142] opened 2017-08-16 09:11 UTC
in 636623-zen, a user asked if we provided this feature and, while we don't currently, I think it might be neat to add. Essentially, we could generate reports for this kind of information: 

1. How many jobs posted (in a day/weeks/months) 
2. How many candidates registration (in a day/weeks/months) 
3. Sales summary (from listing charges) 

For 3, I'm guessing this can be done in woo so we'd just have to pull that info in.

**Comment by jom** [comment] 2017-08-16 10:18
In the implementation of this, it'd be nice to do the first one in core and then have the second (applications add-on) and third (wc-paid-listings/simple-paid-listings) hook into the behavior in core. The 3rd example report should technically be possible right now in WooCommerce, but we could add some additional metrics to our report view.

**Comment by wpfan2099** [comment] 2017-12-11 10:13
sounds very very interesting - i would love to see this feature coming!!! Many thanks for bringing this up to awareness. '

**Comment by jom** [comment] 2018-03-27 23:15
Duplicate of #695

**Closed by jom** 2018-03-27 23:15 UTC
Labels: Feature, Enhancement
