### ISSUE TITLE
Ajax loading TOO SLOW for search_location for more than 100K jobs in the system

### ISSUE THREAD

**Issue by css1323** [Automattic/WP-Job-Manager#2365] opened 2023-01-25 12:57 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.1.1
- WP Job Manager Version:1.39.0
- PHP Version: 7.4
- Other important details: 

My website is turn-to.com and when i type in arizona and select the value of arizona united states it takes about 10 to 15 seconds to load. It takes time on the location only particularly, cache is also enabled, have been facing this once more jobs were added.

![WhatsApp Image 2023-01-25 at 18 26 20](https://user-images.githubusercontent.com/57360248/214569001-5c0e09a6-7f84-4979-964b-a2df23e8cc38.jpeg)
It takes about 10 seconds to load. Please see to it if it is coming from wp job manager or workscout. I have posted the same issue over workscout too.

**Comment by css1323** [comment] 2023-01-30 14:15
any update on the issue?

**Comment by css1323** [comment] 2023-02-06 16:54
any update on this ?

**Comment by tripflex** [comment] 2023-02-23 22:50
I suggest installing my empty meta cleanup (free) and look at bottom of page for details on how to optimize your database https://plugins.smyl.es/blog/empty-meta-cleanup-free-plugin-released/

**Comment by tripflex** [comment] 2023-02-23 22:50
If you're using a low end hosting company chances are you're also sharing resources with other users, or may be time to look at using a performance based host

**Comment by css1323** [comment] 2023-02-24 04:47
Hi,

I am using cloud hosting with 48Gb ram high frequency server by vultr. The
speed for ajax loads within 1 second across all other inputs. Just that
location with radius filter ON takes too much load on the server

**Comment by tripflex** [comment] 2023-03-03 03:27
Radius is not a native feature.  Are you using my plugin or some other theme that adds this feature?

**Comment by css1323** [comment] 2023-03-06 15:29
We are using the Workscout theme inside, so it connects to the wp job
manager also.





*-Best Regards,Shikhar ShahTech EntrepreneurMobile: +91-9727069323*
*Whatsapp: * *https://wa.me/919727069323* <https://wa.me/919727069323>



*www.findcss.com <https://www.findcss.com>Email: ***@***.***
***@***.***>*

**Comment by gikaragia** [comment] 2023-06-02 09:00
Duplicate of https://github.com/Automattic/WP-Job-Manager/issues/2386

**Closed as completed by gikaragia** 2023-06-02 09:00 UTC
Labels: Bug
