### ISSUE TITLE
Editing job in backend allows for multiple types

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#549] opened 2015-10-27 14:06 UTC
... but we enforce a " one type per job" policy on the default submission form:

![screen shot 2015-10-27 at 10 02 43 am](https://cloud.githubusercontent.com/assets/5512652/10760231/e09474e4-7c91-11e5-8a65-eefd36da5d62.png)

This leads to confusion:

https://wordpress.org/support/topic/bug-single-job-listing-page-only-displays-first-type

https://wordpress.org/support/topic/multiple-job-types

https://wordpress.org/support/topic/multiple-job-types-1

We should either allow multiple job types per job or limit the backend meta box in such as way as to enforce the "one type per job" rule.

**Comment by aheckler** [comment] 2015-10-27 14:08
In case I end up looking into this myself: http://code.tutsplus.com/articles/how-to-use-radio-buttons-with-taxonomies--wp-24779

**Comment by mikejolley** [comment] 2015-11-03 13:24
https://core.trac.wordpress.org/ticket/14877

**Comment by donnchawp** [comment] 2016-10-10 16:48
Here's what looks like an extensive class for changing the category/taxonomy box to radio:
https://github.com/WebDevStudios/Taxonomy_Single_Term

I've also come across Javascript that goes through the elements of the box changing each to a radio checkbox, but that seems a bit hacky to me. There's even a plugin that does that here: https://wordpress.org/plugins/change-category-checkbox-to-radio-button/

My preference is to try the class above or use the code @aheckler found.

**Comment by donnchawp** [comment] 2016-10-11 17:55
In #781 I used the code from the tutorial @aheckler found to change the checkboxes into radio buttons but I'd appreciate some eyes on it before merging.

**Comment by donnchawp** [comment] 2016-10-12 08:04
Also, I wonder if any users are using this functionality to have more than one job type? If we wanted to support more than just jobs in the future this would be limiting, unless we start to support tags.

**Comment by spencerfinnell** [comment] 2016-10-12 10:20
I don't see it a lot since the output function only supports one type, however there have been people who requested that functionality. Perhaps a filter to disable for people who have modified or created their own way to output multiple?

**Comment by donnchawp** [comment] 2016-10-12 11:50
It would be easy to add a filter that returns true by default so the remove/add metabox calls are executed [here](https://github.com/Automattic/WP-Job-Manager/pull/781/files#diff-c117e2e96cdacd51451ce7c82afd7bafR126). 

It's probably best to make single job type the default as it's the default on the public submission page.

**Comment by eppul** [comment] 2016-10-12 12:03
I thinks it is important to have multiple job types for more precise classification. So I would not force single job type but make it optional.

For example I could have Job that is part-time and also summer job at the same time.

I have already changed the front-end submission form to support multiple job types with the "WP Job Manager - Field Editor" and I have changed the front-end templates and some functions to support displaying of multiple job types.

Please don't force single "Job Type". There could be lot of different situations where one would want to use multiple job types.

If wanted I can paste the changes that I made to achieve displaying of multiple job types on the front-end.

**Comment by donnchawp** [comment] 2016-10-12 12:37
eppul - thanks for your comment! I'd be very interested in hearing about what changes you made to the front end.

It might be better to allow either multi or single selection of job types since they're the only taxonomy allowed currently. That could be a checkbox setting on the settings page that would change the UI in the backend and frontend.

**Comment by eppul** [comment] 2016-10-12 12:49
I copied couple of functions and changed them to suit my needs.

Here are the modified functions.

`/**
 * Output multiple job types
 *
 * @since 1.0.0
 */

function output_multiple_job_types ( $post = null ) {

	$arrayOfJobType = get_the_job_type_new($post); //get the job type array value from get_the_job_type_new()

		foreach( $arrayOfJobType as $listNameItem ){
				$output4 = $listNameItem->slug; //output only slug from the array type item
				$output5 = $listNameItem->name; //output only real name
				$output5 = str_replace('/', '/<wbr>', $output5); //output with correct word wrapping
				echo '<li class="job-type ' . sanitize_title($output4) . '" itemprop="employmentType">' . $output5 . '</li>';
		}

}

/**
 * get_the_job_type_new function.
 *
 * @access public
 * @param mixed $post (default: null)
 * @return void
 */
function get_the_job_type_new( $post = null ) {
	$post = get_post( $post );
	if ( $post->post_type !== 'job_listing' ) {
		return;
	}

	$types = wp_get_post_terms( $post->ID, 'job_listing_type' );

	if ( $types ) {				

			$type = array(); //change type to return array
			foreach($types as $typesItem) {
 				$type[] = $typesItem;
			}
			
	} else {
		$type = false;
	}

	return apply_filters( 'the_job_type_new', $type, $post );
}`

And I just load it inside the head meta (content-single-job-meta.php) and listing template(content-job-listing.php) with this:
`<?php output_multiple_job_types();?>`

Thank you for you consideration

**Comment by donnchawp** [comment] 2016-10-12 13:16
Thanks for that. It's useful!

If we're going down this route, we should extend get_the_job_type() so it returns multiple job types if necessary. The code in the templates will have to be updated (and possibly merged, since the same code is used in several files), and the job submission form will have to be updated too of course.

**Comment by davoraltman** [comment] 2016-10-12 17:39
> It might be better to allow either multi or single selection of job types since they're the only taxonomy allowed currently. That could be a checkbox setting on the settings page that would change the UI in the backend and frontend.

@donnchawp Adding it as a setting inside Job Submission sounds great! The default should be one job type but users should also be able to enable multiple job type selection.

**Comment by donnchawp** [comment] 2016-10-13 12:55
I updated my PR so it adds a new setting to the Job Submission page. I added a function that checks that setting and then use that function to modify the post editor and front end job submission form.

![screen shot 2016-10-13 at 13 54 09](https://cloud.githubusercontent.com/assets/5656673/19349762/ad9bc030-914c-11e6-9b5f-134d77e29248.png)

I'm not too happy with the wording of that setting so if anyone has suggestions I'd love to hear them!

**Comment by aheckler** [comment] 2016-10-13 12:58
What about this?

> Allow each job to have only one job type

**Comment by spencerfinnell** [comment] 2016-10-13 13:45
I think it should be off by default (like multiple categories) and then mirror the multiple category text.

**Comment by donnchawp** [comment] 2016-10-13 14:23
Not everyone will be happy with this change, and we'll have to make it prominent for users upgrading, but I'd rather stick with the way it is now. 

Forcing one job type will inconvenience users who use wp-admin but at least they can find the Settings page and toggle the setting. If we enable multiple job types by default the frontend submission form will be modified, possibly without a site owner noticing until too late when submitted jobs have multiple types. The single setting means the frontend form remains the same so if the form has been modified at the DOM level in the past that hack will still work.

@aheckler - thanks, you got me thinking in the other direction! Since we're putting a limit on what the user can do rather than letting them have free reign over how many types they can use. I think we could call the setting:

> Limit Jobs to one job type each

**Comment by spencerfinnell** [comment] 2016-10-13 14:32
Sorry, I meant off by default when the setting toggles multiple types on. So the setting would be the opposite of what you have currently.

"Multi-select Types: Enable multiple types for listings"

So with it off by default only the admin will change to what was the expected behavior previously (submit one type on the frontend, select one type on the backend).

Then when you toggle it on the admin "reverts" (to how it is now) and the frontend updates to a multi-select. 

Then it's a matter of dealing with the template files.

**Comment by donnchawp** [comment] 2016-10-13 15:38
Ah, so we're saying the same thing but the opposite wording for the settings page? I'm inclined to leave it the way it is however (well, except to slightly change the wording as I suggested above). I don't think it makes it any clearer or easier to understand.

**Comment by spencerfinnell** [comment] 2016-10-13 16:07
By itself it might not be any clearer but I think in the context of the other settings it makes more sense to match it to the same toggle as categories.

Toggle On: Turn __on__ multiple categories
Toggle On: Turn __off__ multiple types

Those settings really do the same thing but they contradict each other in how they are used.

**Comment by donnchawp** [comment] 2016-10-14 10:31
OK, I have you now, and that makes sense. Thanks for persisting!

In fact I think the "job type" setting should probably go under the category settings on the "Job Listings" settings tab, since they are related.

**Closed** 2016-10-17 11:13 UTC
Labels: [Pri] Normal, [Type] Bug
