### ISSUE TITLE
Require an account to submit listings - doesnt work

### ISSUE THREAD

**Issue by Gaxuxa** [Automattic/WP-Job-Manager#1321] opened 2018-02-13 09:46 UTC
Hello, 
I don't select "Require an account to submit listings"  but in the  "submit a job" page it appear 
![capture d ecran 2018-02-13 10 44 58](https://user-images.githubusercontent.com/36439954/36143326-123a8aa6-10ab-11e8-825f-4913a000997f.png)
![capture d ecran 2018-02-13 10 44 00](https://user-images.githubusercontent.com/36439954/36143327-127ee494-10ab-11e8-9240-1dc2a7f3d0f8.png)

**Comment by jom** [comment] 2018-02-13 09:47
Try to verify with Twenty-Seventeen theme. It may be a theme issue...

**Comment by iamgabrielma** [comment] 2018-09-03 09:40
Closing this as we had no follow-up from the author since February. 

If you're still experiencing this problem please be sure to share reproducible steps to so we can take a look into it, as well as deactivate all plugins except WP Job Manager, switching themes to a default WordPress theme like Twenty Sixteen, and testing again to check if is a conflict.

**Closed by iamgabrielma** 2018-09-03 09:40 UTC
Labels: [Status] Needs Author Reply
