### ISSUE TITLE
Expiration date changes to current day and immediately expires

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/WP-Job-Manager#898] opened 2017-03-16 04:47 UTC
This is mostly a placeholder until I can test this myself, but it appears the recent plugin update might have broken the listing expiration functionality where listings are automatically expired to the current date and expire almost immediately.

Reported in 3111459-t

**Comment by rachelsquirrel** [comment] 2017-03-29 12:39
A similar report in #3121019-t except the expiry date moves one date back from the original date each time they edit the listing. For example if the expiry is April 15 it will change to April 14 when they edit the listing.

**Comment by spencerfinnell** [comment] 2017-03-29 13:45
Duplicate of https://github.com/Automattic/WP-Job-Manager/issues/869 and fixed in https://github.com/Automattic/WP-Job-Manager/pull/903

**Closed by spencerfinnell** 2017-03-29 13:45 UTC
Labels: [Pri] High, [Type] Bug
