### ISSUE TITLE
BUG - Posting two jobs in a row overwrites the previous pending job offer

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#835] opened 2016-12-14 15:59 UTC
#### What Happens

When I publish two jobs in a row which are not publish right away (pending payement e.g.) the second job overwrites the first one. Woocommerce creates two customer orders but in both cases the Post-ID for both jobs are the same. The first job is lost.

#### Steps to Reproduce the Bug

Use Wp Jobmanager with WC-Paid-Listing Addon. As a guest create a first new job -> Preview it -> Publish Listing -> Fill Order Form and save. Then do the same again -> create a new job -> Preview -it -> Publish listing -> Fill Order Form and Save. Now this new jobs overwrites the existing one. 

It gets even crazier as it is not related to one user. Means I can create a job as User A which is pending and then a User B creates also a job and it simply overwrites the pending job offer of User A.

So its quite an important issue...as it seems that the system allows only one pending job offer at a time.

BR Lens

**Comment by eppul** [comment] 2016-12-15 08:53
It seems to me that Automattic should go another round of hard core bug hunting/fixing.
It has taken too long since the last update.

**Comment by Lens40** [comment] 2016-12-20 13:28
After some research we found possible reasons for the issue. In the submit form we have following code:  
`if ( ( 'preview' === $job_status || 'pending_payment' === $job_status ) && get_post_meta( $job_id, 'submitting_key', true ) === $_COOKIE['wp-job-manager-submitting-job-key'] ) {
$this->jobid = $job_id;
}`

Means that when a user starts creating a job and does not publish it the cookie will save the infos so that when he returns to the submit form he edits the same job. The idea is good but there is an issue:

When you use WC-Paid-Listing the job status stays in "preview" after submitting the job even though I would expect it to change to "pending_payement" (bug?). So even though the user has submitted the job as long as the job has not been changed to published he will always edit its current job even though he thinks he is creating a second one. Unfortunatley WC-paid-Listings doesn't make a difference and makes the user pay a second time even though he just edited his current order by mistake.

I guess that without WC-Paid-Listings you might have the same issue when the admin needs to confirm the job publication if the status stays in preview.

**Comment by kochhase** [comment] 2016-12-21 01:32
Hi there you are right. this will only work, when you pay via paypal etc. That the job is paid, and the user is been able to take the next job to enter. but at the BtoB business you use an invoice and the paying going later. so I think it would better if the job status would thange to "pending_payement" after submitting the job even though.
I hope that Mike would look here in this area. last year there was all better...

**Comment by donnchawp** [comment] 2016-12-21 15:20
It took a while to replicate this. From my testing you have to uncheck the following in the plugin settings page:
* Submitting listings requires an account
* Allow account creation
* Automatically Generate Username from Email Address

The paid listing plugin wanted me to create a user account at the end of the purchase so maybe it should change the settings above in WPJM when installed? The user created by the payment plugin had a role "Customer", while the one created by WPJM is "Employer", but both classes of user have to buy a package to post a job. I say this but I agree that the core issue should be fixed.

**Comment by Lens40** [comment] 2016-12-21 15:50
Hi Don thanks for your feedback. I'll have a look at this as I guess that I have all these fields checked.

**Comment by donnchawp** [comment] 2016-12-21 17:12
You're right about the cookie based auth system though. It only allows one "pending" job per guest user. The plugin really should send an email to the person submitting the job with a link to edit the job. The link would have the post_id and a secret key.

**Comment by Lens40** [comment] 2016-12-21 17:32
Are you sure it is just guest user related? This would mean that it shouldn't happen as a logged user? In our case a guest user created the first job and submitted it. By submitting it he became a registered user "Employer" and when he started posting the second job it would still updated the main data  of the previous job. It seems that under those circumstances the cookie still sets the job ID and the post-author. I have to test how WPJM behaves if the user is already logged  when he creates the first job.

**Comment by donnchawp** [comment] 2016-12-21 18:16
I'm pretty sure. I submitted one job as a not logged in user, but checked all the boxes above (Submitting listings requires an account, etc). Two jobs were created. I used the same browser window to submit both.

Then, I unchecked "Submitting listings requires an account" and as a guest I submitted a job, bought a job placement and paid for it. That was job_id 64.
I was then logged in when I went back to the submit page and did the same, creating a new job, and that got job_id 66. I went through the whole process and it was still a separate job at the end. So it looks like the cookie messes up the anonymous job submit code.

The "Allow account creation" setting creates the WordPress account. Do you have that checked?

**Comment by Lens40** [comment] 2016-12-22 09:47
Hi Donn thanks for checking. Have you paid with Paypal Sandbox? In our case all our jobs are set to be paid by bank transfer. So when the user starts creating a new job before we confirm the order it will stay in preview or pending_payement. In our case the job is only published by the admin via Woocommerce by changing the order to "Order completed". Means that if we do not validate the order the job would update the previous job.

Please note that the user uses a one job pack and not a job pack with several jobs: 

User goes to website -> selects to publish one job (we have set WPJM in a way that the user first selects its job pack) -> Fills in the job form -> Preview the job -> Submit the job -> Fills in the order details -> Selects bank transfer -> Sends order

once he has done that he does the same again

 At least that is what we experienced so far. But I will do further testing.

**Comment by Lens40** [comment] 2016-12-22 09:48
Please note that is the behavior with "Allow account creation" activated.

**Comment by kochhase** [comment] 2016-12-22 11:24
Hi donnchawp,

I said before "I think it would better if the job status would thange to "pending_payement" after submitting the job even though." but thats the status right now. It had to be the next level. Something like "processing". 
the reason why:
If you have more than 1 Job per package than the user has the problem, that he could not see a "free" jobpackage after filling out his first job. This is not good for jobpackage buyers who want to give two or more ads at once.

**Comment by donnchawp** [comment] 2016-12-22 14:15
Thanks @Lens40. I enabled payment by check and see the pending_payment is the post status. 

It is the cookie, but it's also doing what it's supposed to be doing. When I reload the post-a-job page it shows me the details for the job I just entered so I could edit it again. Did it do that for you? I opened a new Incognito window and I wasn't logged in so I was able to create a brand new job.

What we really need to do is get away from using the cookie and use a URL, or the post-a-job form should show a message at the top saying something like, "Still editing job X. Click NEW JOB to create a new entry." with a button below it named "NEW JOB".

@kochhase - I think that's a separate issue isn't it? We're trying to stop WPJM overwriting the job record here. Can you open a new ticket about that?

**Comment by Lens40** [comment] 2016-12-22 14:30
@donnchawp thanks, yes I guess we should move away from the cookie, because how should a user be able to post five jobs in a row if he only can edit the first one until it is published. So yes in our case the customer "edited" his existing job thinking he would publish a new one. What eles should he think if he is on the post-a-job page selects to post a new job and then sees the job form, even though it is prefilled with the previous job.  WC-Paid-Listing also creates a new order in this case so for the user it seems as he had created two jobs and two orders. But in the end it is just one job with two orders...

**Comment by Lens40** [comment] 2016-12-22 14:34
Especially for logged users it should be easy to show the jobs in the "Job Management Area" as pending Payements and they can edit it from there.

**Comment by Lens40** [comment] 2016-12-22 14:41
Maybe the issue can be fixed with more job status, as the cookie is probably needed when you are on the preview and you still want to edit the job using the "Edit" button.

Maybe we would need:

a) Preview (for preview)
b) Submitted/Approval (When user has submitted the job but it is pending approval from admin -> Edit only via account or URL with token.) I guess this one is missing, as with WC-Paid-Listing the job stays in preview until order is placed.
c) Pending_Payment (When WC-Paid-Listing is present and the order is created as it is currently the case -> Edit only via account or URL with token.)

**Comment by donnchawp** [comment] 2016-12-22 15:03
The cookie isn't needed when normally editing as the submit buttons pass on the post_id in the form, or at least should. I haven't looked at that code in a while. More information for the user when they come back to the "post a job" page would clear up most of the confusion caused by this.

I think the core plugin shouldn't know anything about the "pending_payment" status. There should be a filter anywhere where that status is used. The filter would be called something like "is_job_pending", so the paid listing plugin would hook on to it and return true if the status was pending_payment.
We could then have a WC-now-flying plugin where jobs could only be bought while flying through the air on a trampoline. (I joke, but you get the idea!)

**Comment by donnchawp** [comment] 2016-12-22 16:49
I just checked in code above that warns the user if they're editing an existing job. It's simple and needs styling. I'm not too happy where I put the code that clears the cookie in the functions file but I needed somewhere that loaded before html was shown. I guess it should go into a function called by the plugin constructor really.

When the "Create a new job" link is clicked it deletes the associated cookies, and deletes the postmeta record used as a key. That key is used as a means of authenticating the link click too.

One for the todo list: the _submitting_key postmeta field is never deleted AFAICT. It could be when a job is published.

**Comment by spencerfinnell** [comment] 2016-12-22 16:59
Agreed, it should go in the form abstract and called in the abstract constructor. 

Would be nice if it used the `add_error()` method in the form class as well (or a similar notice alert type) was added so it's output in the same location, can be modified, etc.

**Comment by Lens40** [comment] 2016-12-22 17:00
Thanks for the patch we will test it after Christmas. Have a nice holiday
!

**Comment by Lens40** [comment] 2016-12-28 10:14
Hi @donnchawp, we just tested the patch. And it needs a small modification to work when WC-Paid-Listing is setup to first choose a plan and then create the job:

We needed to remove `&& ! $this->job_id` from line 93 in includes/forms/class-wp-job-manager-form-submit-job.php

**Comment by donnchawp** [comment] 2017-02-22 12:11
@Lens40 - I don't think it's not as simple as that unfortunately. That will stop it working correctly if the package is selected after the job is entered. I had to check the "job_manager_paid_listings_flow" option in that line to get it working correctly.

However, to further complicate things, if someone does continue to edit the job and enter new details they'll update the job but they'll have to pay for a whole new subscription, at least in my testing.

So, if the resumed job has a post_status of "pending_payment" I think we should clear the cookie, and force the user to enter a new job.

The employer really should be emailed a link with a secret key to be allowed to edit an existing job instead of using a cookie.

**Comment by donnchawp** [comment] 2017-02-22 18:21
I just updated #847 - it checks if packages are set to show first and moved the cookie reset code around.

In the future I think we should get rid of the cookie completely and email the employer a link to edit the job if they need to. An email is less likely to get lost than cookies in a browser but that's something for another issue.

**Comment by jom** [comment] 2017-05-12 17:32
Closing, but tracking @donnchawp's email notification enhancement in #964

**Closed by jom** 2017-05-12 17:32 UTC
Labels: [Pri] Normal, [Status] Needs Dev Review, [Type] Bug
