### ISSUE TITLE
show_pagination broken on jobs shortcode

### ISSUE THREAD

**Issue by SimonB2011** [Automattic/WP-Job-Manager#1000] opened 2017-05-26 15:31 UTC
#### What I Expected To Happen
When using [jobs show_pagination=true] for the pagination to be displayed

#### What Happened Instead
pagination is never shown

#### Steps to Reproduce the Bug
try using the short code [jobs show_pagination=true]
Wordpress version 4.7.5
WP Job manager 1.26.0

It appears the bug is caused when the variable $show_pagination is converted from a String to a Boolean
Running strlen on $show_pagination when true is set shows that it's 11 characters long.  This stops the in_array (in string_to_bool) from identifying that it is supposed to be true and so it is always defaulted to false.

**Comment by jom** [comment] 2017-11-22 14:06
I'm not able to reproduce. Nothing has changed with that code, though, so I'm not sure what was causing this. Are you still able to reproduce this? Closing for now.

**Closed by jom** 2017-11-22 14:06 UTC
