### ISSUE TITLE
My job list show on two pages using default language only

### ISSUE THREAD

**Issue by EngMs** [Automattic/WP-Job-Manager#839] opened 2016-12-18 06:58 UTC
I’m having issues with wp job language plugin and polylang plugin
My job list show on two pages using default language only 

Default Language: Arabic
Second Language: English

Jobs In Default Language (Arabic) : http://athwaqest.com/%D8%A7%D9%84%D8%AA%D9%88%D8%B8%D9%8A%D9%81/
Jobs In Another Language (English) :http://athwaqest.com/en/employment/

**Comment by kraftbj** [comment] 2016-12-19 16:22
Duplicate of #754

**Closed by kraftbj** 2016-12-19 16:22 UTC

**Comment by EngMs** [comment] 2016-12-19 22:51
I try this solution https://github.com/Automattic/WP-Job-Manager/issues/832
 but nothing change

**Comment by kochhase** [comment] 2016-12-21 01:43
Hi EngMS,
maybe go back to polylang 2.05. That what i have done for fixing that problem. after 2.05 the WP Job Manager is not working as before.

**Comment by EngMs** [comment] 2016-12-21 06:35
Hi Kochhase,
I installed polylang  2.05 but nothing changes and still i am having the same issue 

Jobs In Default Language (Arabic) : http://athwaqest.com/%D8%A7%D9%84%D8%AA%D9%88%D8%B8%D9%8A%D9%81/
Jobs In Another Language (English) :http://athwaqest.com/en/employment/
