### ISSUE TITLE
Extend listing / relist

### ISSUE THREAD

**Issue by ICONSdigital** [Automattic/WP-Job-Manager#880] opened 2017-02-22 09:20 UTC
#### What I Expected To Happen
We set jobs with a fixed number of days, 7 days prior to expiration the job poster gets an email (Smyles email notification plugin) which leads him to the job dashboard. (We don't use paid listings, all are free.) I expected to see a renew / extend listing possibility.

#### What Happened Instead
If the job hasn't expired yet it isn;t possible to add extra days (extend the listing), when the job has expired you can't do anything anymore.

#### Steps to Reproduce the Bug
Try to renew using the front end.

How can we add an option for letting users renew their job listing?

**Comment by spencerfinnell** [comment] 2017-03-02 14:09
Duplicate of #848

**Closed by spencerfinnell** 2017-03-02 14:09 UTC
