### ISSUE TITLE
Admin: Re-Approve Resume and Job-Listing after Edit or Update

### ISSUE THREAD

**Issue by ET-Mod** [Automattic/WP-Job-Manager#1322] opened 2018-02-13 10:03 UTC
I'm using Jobify Theme with WP Job Manager and WP Resume Manager
I tried all the plugins I could find that I compatible with my WordPress none of work.
I simply want the Admin to approve Job listing and Resume after editing  or update.

I also tried more codes on my functions.php and still nnot working
add_action('save_post', 'submit_for_review_update', 25 );
 
function submit_for_review_update($post_id) {
 
    if (empty($resume_id)) {
        return;
    }
 
    $resume = get_post($resume_id);
    if (!is_object($resume)) { 
        return;
    }
 
    if ($resume->post_type=='revision') {
       return;
    }
 
    $current_user = wp_get_current_user();    
    if (in_array('author', $current_user->roles) && $resume->post_status=='publish') {
        $mresume_post = array(
            'ID' => $resume_id,
            'post_status' => 'pending',
        );
 
        remove_action('save_post', 'submit_for_review_update', 25);
        wp_update_post($resume_post);
        add_action('save_post', 'submit_for_review_update', 25);
    }
}

Please help.

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment] 2018-02-13 10:05
Duplicate of #509. Coming in 1.30.0 for WPJM core (already merged into master). No set plan for Resumes, but this is just for WP Job Manager core issues.

**Closed by jom** 2018-02-13 10:05 UTC
