### ISSUE TITLE
Continue Submission(draft) results in new listing

### ISSUE THREAD

**Issue by shemakeswebthings** [Automattic/WP-Job-Manager#1811] opened 2019-06-28 00:19 UTC
#### Steps to Reproduce
1. Login to an account
2. Post a job
3. From ~~the Job Dashboard~~ the job listings in WP-Admin, change the job from active to draft
4. Job details on the draft are reset, you are taken through the process again to submit your job
5. Job Dashboard results in:
 - original job draft(still reads, continue submission)
 - submitted job that was created as a result of trying to finish your original draft listing

#### What I Expected
Complete submission link should take user back to the saved draft.

#### What Happened Instead
 I am using WC Paid Listings - I'm not sure if that's creating a conflict. When I try to complete a job listing submission I am asked to choose a listing package again and all of the previously input listing data is gone.

**Comment by richardmtl** [comment] 2019-07-02 16:27
Hi! Did you send us a support ticket? https://wpjobmanager.com/support/

**Comment by shemakeswebthings** [comment] 2019-07-02 16:41
Hi, I haven't as this is a core feature. I believe your support is only for
paid add ons? Are you unable to replicate this issue?

**Comment by richardmtl** [comment] 2019-07-02 18:28
I didn't try yet, I just wanted to ascertain if one of my colleagues had replied to you via email yet or not. :)

> From the Job Dashboard, change the job from active to draft

Hmm, I don't see any way to change an active job listing to Draft from the Job Dashboard. Do you mean from the wp-admin? Or can you show me a screenshot of how you change it to draft on the Job Dashboard? Maybe it's something your theme has added?

**Comment by shemakeswebthings** [comment] 2019-07-02 18:38
From the Wordpress dashboard, not the job dashboard.

If you change an active job to a draft from the Wordpress dashboard users
cannot actually continue the draft from their job dashboard. If they try
to, it will result in a "stuck" draft and a new listing.

I am trying to use this as a way to flag job listings - for example if a
listing is missing some information or provide incorrect links then I want
to be able to change it to a draft to allow users to make changes and
resubmit. Thank you.

**Comment by richardmtl** [comment] 2019-07-02 18:57
Thanks for the clarification! I edited your original submission to clarify. 

I was unable to reproduce what you mentioned; however, I did not have WC Paid Listing active. As such, I'm going to close this issue as it sounds like a bug in WC Paid Listings and not the core plugin. Can you contact us at https://wpjobmanager.com/support/ so that we can get a bit more detail about your WC Paid Listings setup, and then try to reproduce it again? If we can do so, we'll open a bug report for our developers in the right place. Thanks!

**Closed by richardmtl** 2019-07-02 18:57 UTC
Labels: Bug

**Comment by shemakeswebthings** [comment] 2019-07-11 02:15
Hi Richard, it was an issue with my child theme. Sorry for the confusion. Thank you for your help.
