### ISSUE TITLE
The feed including the jobs get Error: invalid feed

### ISSUE THREAD

**Issue by mpanagiotis** [Automattic/WP-Job-Manager#841] opened 2016-12-19 19:44 UTC
#### What I Expected To Happen

Just before udating the WordPress to the latest version 4.7 the feed=job_feed working just fine including the jobs. After the update the feed has been broken and an error occured

#### What Happened Instead

After update WordPress to version 4.7 Error: invalid feed

#### Steps to Reproduce the Bug

http://www.jobseeker.gr/?feed=job_feed

**Comment by kraftbj** [comment] 2016-12-19 21:30
The only way I could duplicate this was when there were no jobs available at all. I'm continuing to look. I had one other report of this this morning via the Indeed job feed integration, but overall not being reported yet.

**Comment by mpanagiotis** [comment] 2016-12-21 11:45
Another point which confirms that there is a issue with the job feed, is that Indeed stopped including my jobs from the day i was update the WordPress to 4.7. http://www.jobseeker.gr/?feed=job_feed&posts_per_page=all  Still looking for a fix but with no luck.

**Comment by kraftbj** [comment] 2016-12-21 15:43
@mpanagiotis Yeah, I'm looking into that too. The Indeed feed is different (assuming you're using that add-on and the indeed-job-feed feed).

**Comment by mpanagiotis** [comment] 2016-12-21 16:54
@kraftbj No i am not using the Indeed add-on. After contact with Indeed I send the default job feed for including my jobs. But after the udate newer jobs not including.

**Comment by edd677** [comment] 2016-12-29 12:16
Can also confirm this issue after upgrading to 4.7. Using the Indeed Plugin the feed /indeed-job-feed feed is not working, and neither is /?feed=job_feed

Thanks,

Ed

**Comment by spencerfinnell** [comment] 2017-01-09 17:59
@kraftbj Having users report this as well. Haven't had time to look in to it myself but getting multiple tickets. Will try to investigate soon.

**Comment by spencerfinnell** [comment] 2017-01-12 15:56
Relevant: https://core.trac.wordpress.org/ticket/39157

However only when there are no posts as @kraftbj mentioned.

**Comment by aheckler** [comment] 2017-01-20 21:43
3008576-t

**Comment by mpanagiotis** [comment] 2017-01-26 21:07
Any update info about the issue?  I have just update to version 4.7.2 but still the feed not working.

**Comment by edd677** [comment] 2017-01-27 09:16
Echo that.

**Comment by rampling** [comment] 2017-02-09 15:20
Echo that again, we really need an answer to this please Dev.... is is resolved and can we upgrade or not please...????

**Comment by edd677** [comment] 2017-02-09 20:30
we rely quite heavily on the feeds for traffic, so this is more than just an inconvenience now. A response would be great - it has been two months now, and I'm sure I'm not the only one on an annual subscription. Thanks!

**Comment by dbtlr** [comment] 2017-02-16 01:28
@edd677, @mpanagiotis I'm currently trying to reproduce this, but having some trouble do so.

If I could get an error log and/or a list of installed plugins that could be helpful. Otherwise, without more information, we're not going to be able to fix this.

For clarities sake, for testing I'm running: WordPress 4.7.2 and WPJobManager@master w/ the 2017 theme.

As with everyone else, I can only reproduce this with an empty feed and that appears to be a core error, not a WPJM error. However, in looking at jobseeker, it seems clear to me that this is not the source of the error since they have jobs posted on their site.

**Comment by spencerfinnell** [comment] 2017-02-16 01:41
Delete your blog posts and you will see it.

**Comment by dbtlr** [comment] 2017-02-16 04:23
It appears that core changed the loading of feeds to be dependant on a `has_posts` check. Adding the `post_type=job_listing` to the query args will fix the page load now. 

I've submitted PR #870 which adjusts the query and adds this by default when loading this feed type. Would love a confirmation that this PR fixes your guys' issues before I merge it.

**Comment by edd677** [comment] 2017-02-16 13:21
@dbtlr - At first I wasn't sure what you wanted me to do, but I appended `&post_type=job_listing` to the section after the domain in the URL `/?feed=job_feed&job_types=contract-temp%2Cfreelance%2Cinternship%2Cpart-time%2Cpermanent&search_location&job_categories&search_keywords`, and this seems to have fixed it.

A perhaps related issue - With the Indeed Integration plugin, the following is producing an invalid feed:

All jobs which are published and non-filled will be included in your feed, and when enabled it will be found at `yoursite.com/indeed-job-feed/’. `yoursite.com/indeed-job-feed/’ is invalid,

**Comment by dbtlr** [comment] 2017-02-16 14:01
That confirmation should be good enough, that the post_type not being set was indeed your issue. Thanks!

**Comment by mpanagiotis** [comment] 2017-02-17 13:27
I also want to confirm that adding the `post_type=job_listing` to the job feed fix the issue. As you can see [http://www.jobseeker.gr/?feed=job_feed&post_type=job_listing&posts_per_page=all]

**Closed** 2017-03-08 15:42 UTC
Labels: [Pri] High, [Status] Needs Author Reply, [Type] Bug

**Comment by dauand** [comment] 2017-03-08 16:19
I have noticed the same issue, which is still not fixed on the RSS link once the search is made, because it generates the URL without `post_type=job_listing`
