### ISSUE TITLE
Enhancement - New Job Draft/Preview - Add Viewable Preview Link

### ISSUE THREAD

**Issue by vetpetjobs** [Automattic/WP-Job-Manager#1654] opened 2019-01-09 23:13 UTC
#### Steps to Reproduce
1. Given the proposed new ability to retain draft Job Ads
2. Create a special "View Only" link so that Managers/Clients can View an Unpublished Draft Job Ad (not logged in to WP)
3. Allow copy and paste link into external email client or simple "Send this link to"
4. No need for any complex approval process, merely to allow third parties (not logged in to WP) to preview a Job Ad prior to publishing
5. Non indexable by Search Engines

#### What I Expected
N/a

#### What Happened Instead
N/a

#### WordPress / WP Job Manager Version
5.01+/WP 1.32.0-beta1

#### Browser / OS Version
All

#### Screenshot / Video
N/a - haven't seen new Draft Job Ad styling

#### Context / Source
We are multi-users of WP Job Manager

**Comment by richardmtl** [comment] 2019-06-20 18:46
Closing as duplicate of #1702 (that one explains things a bit better).

**Closed by richardmtl** 2019-06-20 18:46 UTC
