### ISSUE TITLE
Job Posting for Multiple Location

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1947] opened 2019-12-12 09:15 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

#Job Posting is not considered for multiple location. 
## Suppose some one purchases our job package and they have their offices in different location.
On current situation they need to post a same job for different location.
This is a very basic features every job portals offer to their customers, otherwise they need to spend extra money for a single job post. 
Also job should be visible only for one location, say I have posted a job where multiple vacancies available for Delhi, Mumbai & Chennai offices.
On Current situation it will only shows for a single location. So candidate will not able to find the jobs available for their city.
Think about this.
Shuvashish

**Describe alternatives you've considered**

**Additional context**

**Comment by jom** [comment] 2019-12-12 10:17
Duplicate of #890

**Closed by jom** 2019-12-12 10:17 UTC
